/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* tdr version: 2.7.16 */


using System;
using System.Diagnostics;

namespace MissQ.Tools
{

    internal class TdrDebug
    {
        public static void tdrTrace()
        {
            StackTrace st = new StackTrace(true);
            for (int i = 1; i < st.FrameCount; i++)
            {
                if (null != st.GetFrame(i).GetFileName())
                {
                    Console.WriteLine("TSF4G_TRACE:  " + st.GetFrame(i).ToString());
                }
            }
        }
    }
}
