git subtree pull --prefix Client/Packages/openngs.build https://git.eegames.net/openngs/client/openngs.build.git main
git subtree pull --prefix Client/Packages/openngs.core https://git.eegames.net/openngs/client/openngs.core.git main
git subtree pull --prefix Client/Packages/openngs.data https://git.eegames.net/openngs/client/openngs.data.git main
git subtree pull --prefix Client/Packages/openngs.savedata https://git.eegames.net/openngs/client/openngs.savedata.git main
git subtree pull --prefix Client/Packages/openngs.savedata.playstation https://git.eegames.net/openngs/client/openngs.savedata.playstation.git main
git subtree pull --prefix Client/Packages/openngs.render-piplines https://git.eegames.net/openngs/client/openngs.render-piplines.git main
git subtree pull --prefix Client/Packages/openngs.di https://git.eegames.net/openngs/client/openngs.di.git main
git subtree pull --prefix Client/Packages/openngs.erpc https://git.eegames.net/openngs/client/openngs.erpc.git main
git subtree pull --prefix Client/Packages/openngs.network https://git.eegames.net/openngs/client/openngs.network.git main
git subtree pull --prefix Client/Packages/openngs.protobuf https://git.eegames.net/openngs/client/openngs.protobuf.git main
git subtree pull --prefix Client/Packages/openngs.ui https://git.eegames.net/openngs/client/openngs.ui.git main
git subtree pull --prefix Client/Packages/openngs.game https://git.eegames.net/openngs/client/openngs.game.git main
git subtree pull --prefix Client/Packages/openngs.game.systems https://git.eegames.net/openngs/client/openngs.game.systems.git main
git subtree pull --prefix Client/Packages/openngs.platform https://git.eegames.net/openngs/client/openngs.platform.git main
git subtree pull --prefix Client/Packages/openngs.platform.eegames https://git.eegames.net/openngs/client/openngs.platform.eegames.git main
git subtree pull --prefix Client/Packages/openngs.platform.gcloud https://git.eegames.net/openngs/client/openngs.platform.gcloud.git main
git subtree pull --prefix Client/Packages/openngs.platform.supersdk https://git.eegames.net/openngs/client/openngs.platform.supersdk.git main
git subtree pull --prefix Client/Packages/openngs.battle https://git.eegames.net/openngs/battle/openngs.battle.git main