// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ESProxy.RPC.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable 0612, 0618, 1591, 3021
namespace ESProxy.RPC
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ESCreateReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ESCreateReq()
        {
            indexName = "";
            id = "";
            jsonStr = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string indexName { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string jsonStr { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ESCreateRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ESCreateRsp()
        {
            indexName = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public int errorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string indexName { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ESIndexReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ESIndexReq()
        {
            indexName = "";
            id = "";
            jsonStr = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string indexName { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string jsonStr { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ESIndexRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ESIndexRsp()
        {
            indexName = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public int errorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string indexName { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ESUpdateReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ESUpdateReq()
        {
            indexName = "";
            id = "";
            updateStr = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string indexName { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string updateStr { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ESUpdateRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ESUpdateRsp()
        {
            indexName = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public int errorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string indexName { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ESSearchReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ESSearchReq()
        {
            indexName = "";
            searchStr = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string indexName { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string searchStr { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ESSearchRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ESSearchRsp()
        {
            indexName = "";
            jsonRsp = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public int errorCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string indexName { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string jsonRsp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ESDeleteReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ESDeleteReq()
        {
            indexName = "";
            id = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string indexName { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ESDeleteRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ESDeleteRsp()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public int errorCode { get; set; }

    }

    [OpenNGS.ERPC.Configuration.Service(@"ESProxy.RPC.ESProxyService")]
    public partial interface IESProxyService
    {
        global::System.Threading.Tasks.Task<ESProxy.RPC.ESCreateRsp> ESCreate(ESProxy.RPC.ESCreateReq value, OpenNGS.ERPC.ClientContext context = default(OpenNGS.ERPC.ClientContext));
        global::System.Threading.Tasks.Task<ESProxy.RPC.ESIndexRsp> ESIndex(ESProxy.RPC.ESIndexReq value, OpenNGS.ERPC.ClientContext context = default(OpenNGS.ERPC.ClientContext));
        global::System.Threading.Tasks.Task<ESProxy.RPC.ESUpdateRsp> ESUpdate(ESProxy.RPC.ESUpdateReq value, OpenNGS.ERPC.ClientContext context = default(OpenNGS.ERPC.ClientContext));
        global::System.Threading.Tasks.Task<ESProxy.RPC.ESSearchRsp> ESSearch(ESProxy.RPC.ESSearchReq value, OpenNGS.ERPC.ClientContext context = default(OpenNGS.ERPC.ClientContext));
        global::System.Threading.Tasks.Task<ESProxy.RPC.ESDeleteRsp> ESDelete(ESProxy.RPC.ESDeleteReq value, OpenNGS.ERPC.ClientContext context = default(OpenNGS.ERPC.ClientContext));
    }

}

#pragma warning restore 0612, 0618, 1591, 3021
#endregion
