// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: enums.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Common
{

    [global::ProtoBuf.ProtoContract()]
    public enum GAME_CONSTEXPR
    {
        GAMECONSTEXPR_EMPTYRES = 1,
        GAMECONSTEXPR_PALACETECH = 1,
        GAMECONSTEXPR_PLAYERCITY = 100,
        GAMECONSTEXPR_PLAYERSUBCITY = 101,
        GAMECONSTEXPR_MOUNTAIN = 50,
        GAMECONSTEXPR_WATER = 51,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_MATCH_SCHEME_TYPE
    {
        E_MATCH_SCHEME_ADVENTURE = 1,
        E_MATCH_SCHEME_CHALLENGE = 10,
        E_MATCH_SCHEME_CHAOS = 11,
        E_MATCH_SCHEME_2VE = 12,
        E_MATCH_SCHEME_2V2_PLAYER = 13,
        E_MATCH_SCHEME_2VE_PLAYER = 14,
        E_MATCH_SCHEME_ACTIVITY = 2,
        E_MATCH_SCHEME_RELAXED = 3,
        E_MATCH_SCHEME_ARENA = 4,
        E_MATCH_SCHEME_FIGHT_INVITE = 5,
        E_MATCH_SCHEME_2V2 = 6,
        E_MATCH_SCHEME_PARTY = 7,
        E_MATCH_SCHEME_BO3 = 8,
        E_MATCH_SCHEME_PRACTICE = 9,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_FACTION_TYPE
    {
        E_FACTION_TYPE_None = 0,
        E_FACTION_TYPE_DAWN = 1,
        E_FACTION_TYPE_SUN = 2,
        E_FACTION_TYPE_DUSK = 3,
        E_FACTION_TYPE_NIGHT = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_ITEM_TYPE
    {
        E_ITEM_TYPE_INVALID = 0,
        E_ITEM_TYPE_COIN = 1,
        E_ITEM_TYPE_MONEY = 10,
        E_ITEM_TYPE_FLASH_CARD = 11,
        E_ITEM_TYPE_DRIEDFISH = 12,
        E_ITEM_TYPE_HONORSTAR = 13,
        E_ITEM_TYPE_TASKREDUCE = 14,
        E_ITEM_TYPE_ELITE_BADGE = 15,
        E_ITEM_TYPE_Head = 16,
        E_ITEM_TYPE_HeadBox = 17,
        E_ITEM_TYPE_Expression = 18,
        E_ITEM_TYPE_CardSkin = 19,
        E_ITEM_TYPE_DUST = 2,
        E_ITEM_TYPE_ChallengeKey = 20,
        E_ITEM_TYPE_Bo3Key = 21,
        E_ITEM_TYPE_Currency = 22,
        E_ITEM_TYPE_Guild = 23,
        E_ITEM_TYPE_GUILDROAD_AWARD_LEVEL = 24,
        E_ITEM_TYPE_GUILDROAD_AWARD_TAG = 25,
        E_ITEM_TYPE_GUILDROAD_AWARD_SHOP = 26,
        E_ITEM_TYPE_GUILD_MONEY = 27,
        E_ITEM_TYPE_ACTIVITY_BLACK_GOLD = 28,
        E_ITEM_TYPE_CHOAS_EXCHANGE = 29,
        E_ITEM_TYPE_SKIN_CHIP = 3,
        E_ITEM_TYPE_UNLOCK_ROAD_EX_REWARD = 30,
        E_ITEM_TYPE_UNLOCK_BATTLEPASS_EX_REWARD = 31,
        E_ITEM_TYPE_MALL_TAB = 32,
        E_ITEM_TYPE_MALL_GOODS = 33,
        E_ITEM_TYPE_HERO_CHIP = 4,
        E_ITEM_TYPE_CARD = 5,
        E_ITEM_TYPE_CARD_PACKET = 6,
        E_ITEM_TYPE_PARTY_CURRENCY = 7,
        E_ITEM_TYPE_HERO_SKIN = 8,
        E_ITEM_TYPE_HERO = 9,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_AWARD_OPEN_TYPE
    {
        E_AWARD_ALL = 0,
        E_AWARD_CHOOSE_ONE = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_CARD_ORIGIN
    {
        E_CARD_ORIGIN_EXTENSION = 11,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_MALL_TAB
    {
        E_MALL_TAB_CARDPACKET = 1,
        E_MALL_TAB_HEROSKIN = 2,
        E_MALL_TAB_CRYSTAL = 3,
        E_MALL_TAB_HERO = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_SELL_STATE
    {
        E_SELL_STATE_NORMAL = 1,
        E_SELL_STATE_NOTSELL = 2,
        E_SELL_STATE_NOTSHOW = 3,
        E_SELL_STATE_CDN = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_SELL_START_TYPE
    {
        E_SELL_START_TYPE_INVALID = 0,
        E_SELL_START_TYPE_TIME = 1,
        E_SELL_START_TYPE_PLAYERSTART = 2,
        E_SELL_START_TYPE_SERVERSTART = 3,
        E_SELL_START_TYPE_WHENHAPPENED = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_HONOR_TYPE
    {
        E_HONOR_TYPE_STORM = 1,
        E_HONOR_TYPE_WINNERCOUNT = 10,
        E_HONOR_TYPE_HEROCOUNT = 11,
        E_HONOR_TYPE_FLASHCOUNT = 12,
        E_HONOR_TYPE_STORYCOUNT = 13,
        E_HONOR_TYPE_PARTYCOUNT = 14,
        E_HONOR_TYPE_CHALLANGE_COUNT = 15,
        E_HONOR_TYPE_BO3_COUNT = 16,
        E_HONOR_TYPE_FIERCE = 2,
        E_HONOR_TYPE_MASTER = 3,
        E_HONOR_TYPE_SENIOR = 4,
        E_HONOR_TYPE_RICH = 5,
        E_HONOR_TYPE_DUST = 6,
        E_HONOR_TYPE_POOLCOUNT = 7,
        E_HONOR_TYPE_RANKCOUNT = 8,
        E_HONOR_TYPE_LEVELCOUNT = 9,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_PERIOD_TYPE
    {
        E_PERIOD_FOREVER = 1,
        E_PERIOD_DAY = 2,
        E_PERIOD_WEEK = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_TASK_RARE
    {
        E_TASK_RARE_NORMAL = 1,
        E_TASK_RARE_RARE = 2,
        E_TASK_RARE_EPIC = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_TASK_TYPE
    {
        E_TASK_TYPE_FACTION_WIN = 1,
        E_TASK_TYPE_FIGHT_WIN = 10,
        E_TASK_TYPE_WIN = 100,
        E_TASK_TYPE_CALL_CARD = 11,
        E_TASK_TYPE_CARD_COST_TYPE = 12,
        E_TASK_TYPE_DAILY_TASK_TYPE = 13,
        E_TASK_TYPE_FIGHT_NUM = 14,
        E_TASK_TYPE_GUILD_MATE_FIGHT_NUM = 15,
        E_TASK_TYPE_GUILD_MATE_PARTY_NUM = 16,
        E_TASK_TYPE_FIGHT_SPECIAL_CARD_NUM = 17,
        E_TASK_TYPE_FIGHT_WIN_IN_TIME_NUM = 18,
        E_TASK_TYPE_COST_DRIEDFISH_NUM = 19,
        E_TASK_TYPE_FACTION_CARD = 2,
        E_TASK_TYPE_OPEN_CARD_PACKAGE_NUM = 20,
        E_TASK_TYPE_FIGHT_WIN_BO3_NUM = 21,
        E_TASK_TYPE_FIGHT_HP_ESLE_NUM = 22,
        E_TASK_TYPE_FIGHT_AVG_COST_MORE_NUM = 23,
        E_TASK_TYPE_FIGHT_AVG_COST_LESS_NUM = 24,
        E_TASK_TYPE_FIGHT_RESULT = 25,
        E_TASK_TYPE_FIGHT_FINISH = 26,
        E_TASK_TYPE_LOGIN = 27,
        E_TASK_TYPE_FIGHT_SPECIAL_HERO = 28,
        E_TASK_TYPE_SPECIAL_CARD_TYPE_FORBIDDEN_FIGHT_NUM = 29,
        E_TASK_TYPE_CARD_COST = 3,
        E_TASK_TYPE_SPECIAL_CARD_RARE_FORBIDDEN_FIGHT_NUM = 30,
        E_TASK_TYPE_ANY_GUILD_BOSS_FIGHT_NUM = 31,
        E_TASK_TYPE_ANY_GUILD_BOSS_WIN_NUM = 32,
        E_TASK_TYPE_CARD_TYPE = 4,
        E_TASK_TYPE_HURT_HERO = 5,
        E_TASK_TYPE_KILL = 6,
        E_TASK_TYPE_SKILL = 7,
        E_TASK_TYPE_BOX = 8,
        E_TASK_TYPE_FIGHT_COST = 9,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_TASK_ORIGIN
    {
        E_TASK_ORIGIN_DAILY = 1,
        E_TASK_ORIGIN_DAILY_FIGHT = 2,
        E_TASK_ORIGIN_WEEK = 3,
        E_TASK_ORIGIN_GUILD = 4,
        E_TASK_ORIGIN_ACTIVITY = 5,
        E_TASK_ORIGIN_GUILD_BOSS = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_AI_MOVE_TYPE
    {
        E_AI_MOVE_STAY = 1,
        E_AI_MOVE_NEAR = 2,
        E_AI_MOVE_MIDDLE = 3,
        E_AI_MOVE_FAR = 4,
        E_AI_MOVE_GUARD = 5,
        E_AI_MOVE_ENCHA = 6,
        E_AI_MOVE_BUILDING = 7,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_ACTIVITY_TYPE
    {
        E_ACTIVITY_INVALID = 0,
        E_ACTIVITY_LOGIN_AWARD = 1,
        E_ACTIVITY_EXTRA_REWARD = 10,
        E_ACTIVITY_REWARD_RATE = 11,
        E_ACTIVITY_CHOAS = 12,
        E_ACTIVITY_CUMULATIVE_CHARGE = 13,
        E_ACTIVITY_BOX_LOTTERY = 14,
        E_ACTIVITY_RANK_REWARD = 15,
        E_ACTIVITY_MODEL_PARTI = 16,
        E_ACTIVITY_ARENA_LEVEL = 2,
        E_ACTIVITY_CUMULATIVE_LOGIN = 3,
        E_ACTIVITY_TIME_BUCKET_LOGIN = 4,
        E_ACTIVITY_COMMON_ACTIVITY = 5,
        E_ACTIVITY_GEN_ACCOUNT = 6,
        E_ACTIVITY_NEW_CUMULATIVE_LOGIN = 7,
        E_ACTIVITY_TASK = 8,
        E_ACTIVITY_EXCHANGE = 9,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_CHOAS_CARD_RULE
    {
        E_CHOAS_CARD_NONE = 0,
        E_CHOAS_CARD_COST = 1,
        E_CHOAS_CARD_TYPE = 2,
        E_CHOAS_CARD_RARE = 3,
        E_CHOAS_CARD_FACTION = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_CHOAS_LEVEL_MODE
    {
        E_CHOAS_MODE_NONE = 0,
        E_CHOAS_MODE_HP = 1,
        E_CHOAS_MODE_MP = 2,
        E_CHOAS_MODE_MPMAX = 3,
        E_CHOAS_MODE_MPSPEED = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_AWARD_SEND_TYPE
    {
        E_AWARD_SEND_USER = 0,
        E_AWARD_SEND_DIRECT = 1,
        E_AWARD_SEND_MAIL = 2,
        E_AWARD_SEND_GEN_REWARD_LIST = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_MAIL_TYPE
    {
        E_MAIL_SYSTEM = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_MAIL_RES_ID
    {
        E_MAIL_RES_ID_SYSTEM = 1,
        E_MAIL_RES_ID_LEGEND = 2,
        E_MAIL_RES_ID_SEASON = 3,
        E_MAIL_RES_ID_PARTY_REWARD = 4,
        E_MAIL_RES_ID_PARTY_COIN = 5,
        E_MAIL_RES_ID_LOGINONTIME = 6,
        E_MAIL_RES_ID_RANKUP = 7,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_PARTY_ROOM_TYPE
    {
        E_PARTY_ROOM_CREATE = 1,
        E_PARTY_ROOM_JOIN = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_EMOJI_TYPE
    {
        E_EMOJI_VIEW = 1,
        E_EMOJI_TEXT = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_GETITEMTYPE
    {
        E_DEFAULT = 1,
        E_SYSTEMGIVEN = 2,
        E_BUY = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_CONST_NAME
    {
        E_HONORSTAR_REFRESH_TIME = 1,
        E_BO3_ROUND3_READY_TIME = 10,
        E_BO3_WAIT_TIME_MAX = 11,
        E_E_BO3_CARD_SHOW_TIME = 12,
        E_E_BO3_MATCH_TIME_MAX = 13,
        E_BO3_BOX_LIMIT = 14,
        E_WORLD_CHANNEL_MESSAGE_SEND_INTERVAL = 15,
        E_PARTY_EXIT_DEDUCT_TIME = 16,
        E_WORLD_CHANNEL_MESSAGE_LEN = 17,
        E_WORLD_CHANNEL_MESSAGE_GET_INTERVAL = 18,
        E_GUILD_REJOIN_OR_CREATE_CD = 19,
        E_HONORSTAR_NUM_MAX = 2,
        E_GUILD_CREATE_COST_MONEY = 20,
        E_GUILD_APPLY_LIST_CAP = 21,
        E_GUILD_KICK_MAIL_ID = 22,
        E_GUILD_TASK_REFRESH_TIME = 23,
        E_GUILD_TASK_NUM_MAX = 24,
        E_GUILD_MIN_RANK = 25,
        E_GUILD_REFLESH_ACTIVE_RANK_DAY = 26,
        E_GUILD_REFLESH_ACTIVE_RANK_HOUR = 27,
        E_PARTY_PARTYCOIN_AUTO_GET_LIMT = 28,
        E_COIN_GET_DAILY_LIMT = 29,
        E_BUY_PACK_DAILY_LIMIT = 3,
        E_QQ_GAME_EXTRA_BATTLE_AWARD = 30,
        E_WX_GAME_EXTRA_BATTLE_AWARD = 31,
        E_GUILD_BOSS_DAILY_REFRESH_TIMES = 32,
        E_GUILD_BOSS_TRY_TIMES_REFRESH_TIME_POINT = 33,
        E_GUILD_BOSS_TASK_LIMIT_TIMES = 34,
        E_WX_GAME_EXTRA_LOGIN_AWARD = 35,
        E_QQ_GAME_EXTRA_LOGIN_AWARD = 36,
        E_COIN_GET_ALARM_DAILY_LIMT = 37,
        E_DRIEDFISH_GET_ALARM_DAILY_LIMT = 38,
        E_CHAT_RANK_LIMT = 39,
        E_OPEN_PACK_DAILY_LIMIT = 4,
        E_CHAT_RANK_LIMT_MSG = 40,
        E_TEAM_MATCH_TIME_MAX = 41,
        E_OPEN_SERVICE_DATE = 5,
        E_DAILY_FIGHT_TASK_NUM = 6,
        E_BO3_ROUND1_READY_TIME = 7,
        E_BO3_ROUND2_READY_TIME_WIN = 8,
        E_BO3_ROUND2_READY_TIME_LOSE = 9,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_DIFFICULTY_TYPE
    {
        E_DIFFICULTY_SOLDIER = 1,
        E_DIFFICULTY_KNIGHT = 2,
        E_DIFFICULTY_GENERAL = 3,
        E_DIFFICULTY_LORD = 4,
        E_DIFFICULTY_KING = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_PAY_TYPE
    {
        E_PAY_COIN = 0,
        E_PAY_ITEM = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_GUILD_POSITION_TYPE
    {
        E_GUILD_POSITION_LEADER = 1,
        E_GUILD_POSITION_VICE_LEADER = 2,
        E_GUILD_POSITION_CADRE = 3,
        E_GUILD_POSITION_NORMAL = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_GUILD_ROAD_TYPE
    {
        E_GUILD_ROAD_MEMBER_NUM = 1,
        E_GUILD_ROAD_DUSK = 10,
        E_GUILD_ROAD_TASK_NUM = 2,
        E_GUILD_ROAD_2V2 = 3,
        E_GUILD_ROAD_FRIEND_BATTLE = 4,
        E_GUILD_ROAD_SHOP = 5,
        E_GUILD_ROAD_PARTY = 6,
        E_GUILD_ROAD_SUN = 7,
        E_GUILD_ROAD_NIGHT = 8,
        E_GUILD_ROAD_DAWN = 9,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_GUILD_ROAD_AWARD_TYPE
    {
        E_GUILD_ROAD_AWARD_LEVEL = 1,
        E_GUILD_ROAD_AWARD_TAG = 2,
        E_GUILD_ROAD_AWARD_SHOP = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_STORE_TYPE
    {
        E_STORE_TYPE_None = 0,
        E_STORE_TYPE_Main = 1,
        E_STORE_TYPE_Guild = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_FIGHT_RESULT_TYPE
    {
        E_FIGHT_WIN = 0,
        E_FIGHT_LOSE = 1,
        E_FIGHT_DRAW = 2,
        E_FIGHT_ALL = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_STORE_PAGE_TYPE
    {
        E_STORE_PAGE_RECOMMEND = 0,
        E_STORE_PAGE_CARDPACK = 1,
        E_STORE_PAGE_RECHARGE = 2,
        E_STORE_PAGE_SKIN = 3,
        E_STORE_PAGE_HERO = 4,
        E_STORE_PAGE_DECORATION = 5,
        E_STORE_PAGE_GROCERIES = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_SERVICE_AREA_TYPE
    {
        E_SERVICE_AREA_NONE = -1,
        E_SERVICE_AREA_WX = 0,
        E_SERVICE_AREA_QQ = 1,
        E_SERVICE_AREA_GUEST = 2,
        E_SERVICE_AREA_IOS_AUDIT = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_SYS_FUNC_MODULE_TYPE
    {
        E_SYS_FUNC_MODULE_TYPE_INVALID = 0,
        E_SYS_FUNC_MODULE_TYPE_PAY = 1,
        E_SYS_FUNC_MODULE_TYPE_CREDIT_SCORE = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_SYS_FUNC_SWITCH_TYPE
    {
        E_SYS_FUNC_SWITCH_TYPE_ON = 0,
        E_SYS_FUNC_SWITCH_TYPE_OFF = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_CS_LIMIT_FUNC_ID
    {
        E_CS_LIMIT_FUNC_CHAT = 0,
        E_CS_LIMIT_FUNC_FIGHT = 1,
        E_CS_LIMIT_FUNC_RANK = 2,
        E_CS_LIMIT_FUNC_GUILD = 3,
        E_CS_LIMIT_FUNC_FRIEND = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_ACCOUNT_LIMIT_TYPE
    {
        E_ACCOUNT_LIMIT_NONE = 0,
        E_ACCOUNT_LIMIT_LOGIN = 1,
        E_ACCOUNT_LIMIT_CHAT = 2,
        E_ACCOUNT_LIMIT_RANK = 3,
        E_ACCOUNT_LIMIT_ADD_FRIEND = 4,
        E_ACCOUNT_LIMIT_EDIT = 5,
        E_ACCOUNT_LIMIT_HEAD = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_FEATURE_SWITCH_TYPE
    {
        E_FEATURE_NONE = 0,
        E_FEATURE_GUILD = 1,
        E_FEATURE_WECHAT_CROWN = 10,
        E_FEATURE_WECHAT_LAUNCH_RIGHT = 11,
        E_FEATURE_WECHAT_GIFT_CENTRE = 12,
        E_FEATURE_WEGAME_CIRCLE = 13,
        E_FEATURE_WEMIDIA = 14,
        E_FEATURE_QQ_VIP = 15,
        E_FEATURE_QQ_LAUNCH_RIGHT = 16,
        E_FEATURE_QQ_TRIBE = 17,
        E_FEATURE_QQ_GIFT_CENTRE = 18,
        E_FEATURE_QQ_GROUP = 19,
        E_FEATURE_NOTICE = 2,
        E_FEATURE_MICRO_COMMUNITY = 20,
        E_FEATURE_CONTACT_US = 21,
        E_FEATURE_CLIENT_SERVICE = 22,
        E_FEATURE_HEART_HAPPY_VIP = 23,
        E_FEATURE_CDKEY = 24,
        E_FEATURE_TAPTAP = 25,
        E_FEATURE_CREDIT = 26,
        E_FEATURE_DELETE_ACCOUNT = 27,
        E_FEATURE_QQ_AVATAR = 28,
        E_FEATURE_WECHAT_AVATAR = 29,
        E_FEATURE_SHARE_TO_QQ = 3,
        E_FEATURE_PAY = 30,
        E_FEATURE_SURVEY = 31,
        E_FEATURE_CARD_COMMENT = 32,
        E_FEATURE_GUILD_BOSS = 33,
        E_FEATURE_SHARE_TO_WECHAT = 4,
        E_FEATURE_SHARE_TO_QQ_QRCODE = 5,
        E_FEATURE_SHARE_TO_WECHAT_QRCODE = 6,
        E_FEATURE_2V2 = 7,
        E_FEATURE_2VE = 8,
        E_FEATURE_CHAOS = 9,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_VERSION_TYPE
    {
        E_VERSION_NONE = 0,
        E_VERSION_VS = 1,
        E_VERSION_ALL = 100,
        E_VERSION_ELS = 2,
        E_VERSION_IPS = 3,
        E_VERSION_TBD = 97,
        E_VERSION_MAKING = 98,
        E_VERSION_EXTENTED = 99,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_GUILDBOSS_VOICE_TYPE
    {
        E_VOICE_FIGHT_START = 1,
        E_VOICE_FIGHT_END = 2,
        E_VOICE_FIGHT_WIN = 3,
        E_VOICE_FIGHT_LOSE = 4,
        E_VOICE_BOSS_DANGEROUS = 5,
        E_VOICE_PLAYER_DANGEROUS = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_SHOP_RECOMMEND_CONDITION_TYPE
    {
        E_SHOP_RECOMMEND_CONDITION_NONE = 0,
        E_SHOP_RECOMMEND_CONDITION_AREAN_TOTAL_LOSS = 1,
        E_SHOP_RECOMMEND_CONDITION_SIMBA_FIGHT_NUM = 10,
        E_SHOP_RECOMMEND_CONDITION_SENES_FIGHT_NUM = 11,
        E_SHOP_RECOMMEND_CONDITION_MODRA_FIGHT_NUM = 12,
        E_SHOP_RECOMMEND_CONDITION_DAWN_FIGHT_NUM = 13,
        E_SHOP_RECOMMEND_CONDITION_SUN_FIGHT_NUM = 14,
        E_SHOP_RECOMMEND_CONDITION_DUSK_FIGHT_NUM = 15,
        E_SHOP_RECOMMEND_CONDITION_NIGHT_FIGHT_NUM = 16,
        E_SHOP_RECOMMEND_CONDITION_DAWN_HERO_NUM = 17,
        E_SHOP_RECOMMEND_CONDITION_SUN_HERO_NUM = 18,
        E_SHOP_RECOMMEND_CONDITION_DUSK_HERO_NUM = 19,
        E_SHOP_RECOMMEND_CONDITION_AREAN_CONTINUE_LOSS = 2,
        E_SHOP_RECOMMEND_CONDITION_NIGHT_HERO_NUM = 20,
        E_SHOP_RECOMMEND_CONDITION_POCHI_FIGHT_NUM = 21,
        E_SHOP_RECOMMEND_CONDITION_HATI_FIGHT_NUM = 22,
        E_SHOP_RECOMMEND_CONDITION_TATZEL_FIGHT_NUM = 23,
        E_SHOP_RECOMMEND_CONDITION_MURAD_FIGHT_NUM = 24,
        E_SHOP_RECOMMEND_CONDITION_REACH_ARENA_TIMES = 3,
        E_SHOP_RECOMMEND_CONDITION_CREATE_ACCOUNT_TIME = 4,
        E_SHOP_RECOMMEND_CONDITION_PAY = 5,
        E_SHOP_RECOMMEND_CONDITION_LOGIN_DAYS = 6,
        E_SHOP_RECOMMEND_CONDITION_BUY_SKIN_TIMES = 7,
        E_SHOP_RECOMMEND_CONDITION_FIGHT_NUMS = 8,
        E_SHOP_RECOMMEND_CONDITION_SEAL_FIGHT_NUM = 9,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_CONDITION_OPERATROR
    {
        E_CONDITION_OPE_NONE = 0,
        E_CONDITION_OPE_MORE = 1,
        E_CONDITION_OPE_EQUAL = 2,
        E_CONDITION_OPE_LESS = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum E_CONDITION_RELATION_TYPE
    {
        E_CONDITION_RELATION_AND = 1,
        E_CONDITION_RELATION_OR = 2,
    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
