// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: OpenNGSCommon.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable 0612, 0618, 1591, 3021
namespace OpenNGSCommon
{

    [global::ProtoBuf.ProtoContract()]
    public enum NI_ATTR_TYPE
    {
        VALUE = 0,
        RATIO = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ANNOUNCEMENT_CLICK_TYPE
    {
        ANNOUNCEMENT_CLICK_TYPE_NONE = 0,
        ANNOUNCEMENT_CLICK_TYPE_URL = 1,
        ANNOUNCEMENT_CLICK_TYPE_UI = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ANNOUNCEMENT_CONNDITION_TYPE
    {
        ANNOUNCEMENT_CONNDITION_TYPE_NONE = 0,
        ANNOUNCEMENT_CONNDITION_TYPE_QUEST_UNCOMPLETE = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OBJECT_TYPE
    {
        OBJECT_TYPE_NONE = 0,
        OBJECT_TYPE_PLAYER = 1,
        OBJECT_TYPE_GUILD = 2,
        OBJECT_TYPE_BUILDING = 4,
        OBJECT_TYPE_PET = 8,
        OBJECT_TYPE_CORPS = 16,
        OBJECT_TYPE_TECH = 32,
        OBJECT_TYPE_GLOBAL = 64,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum QUEUE_TYPE
    {
        QUEUE_TYPE_NONE = 0,
        QUEUE_TYPE_RECRUIT = 1,
        QUEUE_TYPE_TECH = 2,
        QUEUE_TYPE_SUB_TECH = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum QUEUE_STATUS
    {
        QUEUE_STATUS_IDLE = 0,
        QUEUE_STATUS_RUNNING = 1,
        QUEUE_STATUS_FINISH = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum QUEUE_UPDATE_TYPE
    {
        QUEUE_UPDATE_TYPE_TIME = 0,
        QUEUE_UPDATE_TYPE_COUNT = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum REWARD_SEND_TYPE
    {
        REWARD_SEND_ITEM = 0,
        REWARD_SEND_MAIL = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum REWARD_TYPE
    {
        REWARD_TYPE_ALL = 0,
        REWARD_TYPE_QUEST = 1,
        REWARD_TYPE_ACHIEVEMENT = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum QUEST_GROUP_TYPE
    {
        QUEST_GROUP_NONE = 0,
        QUEST_GROUP_MAIN = 1,
        QUEST_GROUP_BRANCH = 2,
        QUEST_GROUP_EAERYDAY = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum QUEST_PICK_TYPE
    {
        QUEST_PICK_TYPE_NONE = 0,
        QUEST_PICK_TYPE_RANDOM = 1,
        QUEST_PICK_TYPE_ORDER = 2,
        QUEST_PICK_TYPE_ALL = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum NOTIFY_TYPE
    {
        NOTIFY_TYPE_NONE = 0,
        NOTIFY_TYPE_TIPS = 1,
        NOTIFY_TYPE_MESSAGE_BOX = 2,
        NOTIFY_TYPE_MARQUEE = 4,
        NOTIFY_TYPE_PUSH = 8,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum DIALOG_CHOICE_TYPE
    {
        DIALOG_CHOICE_NONE = 0,
        DIALOG_CHOICE_CANCLE = 1,
        DIALOG_CHOICE_CONFIRM = 2,
        DIALOG_CHOICE_END = 3,
        DIALOG_CHOICE_RANDOM = 4,
        DIALOG_CHOICE_RESULT = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum DIALOG_CHOICE_PARAMTYPE
    {
        DIALOG_CHOICE_PARAMTYPE_NONE = 0,
        DIALOG_CHOICE_PARAMTYPE_EVENT_PARAM = 1,
        DIALOG_CHOICE_PARAMTYPE_EVENT_PROCESS = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum DIALOG_CHOICE_CONDITION
    {
        DIALOG_CHOICE_CONDITION_NONE = 0,
        DIALOG_CHOICE_CONDITION_GE = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum DIALOG_CHOICE_RESULT_TYPE
    {
        DIALOG_CHOICE_RESULT_TYPE_NONE = 0,
        DIALOG_CHOICE_RESULT_TYPE_FINAL = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum DIALOG_EFFECT_FUNCTION
    {
        DIALOG_EFFECT_FUNCTION_NONE = 0,
        DIALOG_EFFECT_FUN_SET_PARAM = 1,
        DIALOG_EFFECT_FUN_GET_CHAR_TYPE = 2,
        DIALOG_EFFECT_FUN_OPEN_UI = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum DIALOG_EFFECT_PARAM_TYPE
    {
        DIALOG_EFFECT_PARAM_TYPE_NONE = 0,
        DIALOG_EFFECT_PARAM_TYPE_VALUE = 1,
        DIALOG_EFFECT_PARAM_TYPE_LIST_ADD = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum QUEST_STATE_TYPE
    {
        QUEST_STATE_TYPE_NONE = 0,
        QUEST_STATE_TYPE_ACCEPTED = 1,
        QUEST_STATE_TYPE_PENDING = 2,
        QUEST_STATE_TYPE_DONE = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OBJECTIVEGROUP_PICK_TYPE
    {
        OBJECTIVEGROUP_PICK_TYPE_NONE = 0,
        OBJECTIVEGROUP_PICK_TYPE_ALL = 1,
        OBJECTIVEGROUP_PICK_TYPE_ORDER = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OBJECTIVEGROUP_OWNER_TYPE
    {
        OBJECTIVEGROUP_OWNER_TYPE_NONE = 0,
        OBJECTIVEGROUP_OWNER_TYPE_PLAYER = 1,
        OBJECTIVEGROUP_OWNER_TYPE_GLOBAL = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OBJECTIVE_FINISH_TYPE
    {
        OBJECTIVE_FINISH_TYPE_NONE = 0,
        OBJECTIVE_FINISH_TYPE_TIMEOUT = 1,
        OBJECTIVE_FINISH_TYPE_SEASON = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OBJECTIVE_FINISH_RELATION_TYPE
    {
        OBJECTIVE_FINISH_RELATION_TYPE_NONE = 0,
        OBJECTIVE_FINISH_RELATION_TYPE_AND = 1,
        OBJECTIVE_FINISH_RELATION_TYPE_OR = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OBJECTIVE_EFFECT_FUNCTION_TYPE
    {
        OBJECTIVE_EFFECT_FUNCTION_TYPE_NONE = 0,
        OBJECTIVE_EFFECT_FUNCTION_UNLOCK_SHOP = 1,
        OBJECTIVE_EFFECT_FUNCTION_UNLOCK_THIEF = 2,
        OBJECTIVE_EFFECT_FUNCTION_UNLOCK_BARBARIANS = 3,
        OBJECTIVE_EFFECT_FUNCTION_BATTLE_EXP = 4,
        OBJECTIVE_EFFECT_FUNCTION_CARD_LEVELUP = 5,
        OBJECTIVE_EFFECT_FUNCTION_THIEF_LEVELUP = 6,
        OBJECTIVE_EFFECT_FUNCTION_POLITICS_EXP = 7,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OBJECTIVE_SYSTEM_TYPE
    {
        OBJECTIVE_SYSTEM_TYPE_NONE = 0,
        OBJECTIVE_SYSTEM_TYPE_ACHIEVEMENT = 1,
        OBJECTIVE_SYSTEM_TYPE_DOMINANCE = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OBJECTIVE_STATE_TYPE
    {
        OBJECTIVE_STATE_TYPE_NONE = 0,
        OBJECTIVE_STATE_TYPE_LOCK = 1,
        OBJECTIVE_STATE_TYPE_ACCEPTED = 2,
        OBJECTIVE_STATE_TYPE_PENDING = 3,
        OBJECTIVE_STATE_TYPE_DONE = 4,
        OBJECTIVE_STATE_TYPE_TIMEOUT = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum RANK_ZONE_RANGE_TYPE
    {
        RANK_ZONE_RANGE_NONE = 0,
        RANK_ZONE_RANGE_SINGLE = 1,
        RANK_ZONE_RANGE_ZONE = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum RANK_OBJECT_TYPE
    {
        RANK_OBJECT_TYPE_NONE = 0,
        RANK_OBJECT_TYPE_CHARACTER = 1,
        RANK_OBJECT_TYPE_GUILD = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum RANK_VALUE_TYPE
    {
        RANK_VALUE_TYPE_NONE = 0,
        RANK_VALUE_TYPE_CHAR_POWER = 1,
        RANK_VALUE_TYPE_GUILD_POWER = 2,
        RANK_VALUE_TYPE_CHAR_TROOP = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum RANK_EVENT_TYPE
    {
        RANK_EVENT_TYPE_NONE = 0,
        RANK_EVENT_TYPE_INIT = 1,
        RANK_EVENT_TYPE_LOGIC = 2,
        RANK_EVENT_TYPE_SEASON = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ACHIEVEMENT_STATUS
    {
        ACHIEVEMENT_STATUS_NONE = 0,
        ACHIEVEMENT_STATUS_STATING = 1,
        ACHIEVEMENT_STATUS_PENDING = 2,
        ACHIEVEMENT_STATUS_DONE = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum REDPOINT_TYPE
    {
        REDPOINT_NONE = 0,
        REDPOINT_NORMAL = 1,
        REDPOINT_NUMBER = 2,
        REDPOINT_ICON = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum STAT_COMP_TYPE
    {
        STAT_COMP_NONE = 0,
        STAT_COMP_GE = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum RANKING_LIFE_TYPE
    {
        RANKING_LIFE_ETERNAL = 0,
        RANKING_LIFE_FIXED_INTERVAL = 1,
        RANKING_LIFE_CONFIGED_INTERVAL = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum RANKING_SCOPE_TYPE
    {
        RANKING_SCOPE_SVR = 0,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum PLAYER_ONLINE_STATUS_TYPE
    {
        OFFLINE = 0,
        ONLINE = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ResultCode
    {
        RESULT_OK = 0,
        RESULT_FAIL = 10000000,
        RESULT_INITINILIZING = 10000001,
        RESULT_LOCKED = 10000002,
        RESULT_INVALID_PARAM = 10,
        RESULT_SERVER_DECODE_ERR = 1,
        RESULT_SERVER_ENCODE_ERR = 2,
        RESULT_SERVER_NOFUNC_ERR = 11,
        RESULT_SERVER_NOENTITY_ERR = 12,
        RESULT_SERVER_INVALID_PARAM = 13,
        RESULT_SERVER_TIMEOUT_ERR = 21,
        RESULT_SERVER_OVERLOAD_ERR = 22,
        RESULT_SERVER_OVER_FLOW_CONTROL_ERR = 23,
        RESULT_SERVER_LOAD_FAIL = 28,
        RESULT_SERVER_UPDATE_FAIL = 29,
        RESULT_SERVER_SAVE_FAIL = 30,
        RESULT_SERVER_SYSTEM_ERR = 31,
        RESULT_SERVER_PLAYER_NOT_FOUND = 32,
        RESULT_CLIENT_INVOKE_TIMEOUT_ERR = 101,
        RESULT_CLIENT_INVOKE_ASYNC_NET_FAIL = 102,
        RESULT_CLIENT_SYSTEM_ERR = 111,
        RESULT_CLIENT_ENCODE_ERR = 121,
        RESULT_CLIENT_DECODE_ERR = 122,
        RESULT_CLIENT_ROUTER_ERR = 131,
        RESULT_CLINET_NETWORK_ERR = 141,
        RESULT_CLINET_NOFUNC_ERR = 151,
        RESULT_CLIENT_OVER_FLOW_CONTROL_ERR = 161,
        RESULT_TIMER_INVALID_PARA = 200,
        RESULT_TIMER_INEXISTENT = 201,
        RESULT_REGISTER_METHOD_FAIL = 202,
        RESULT_UNKNOWN_ERR = 999,
        RESULT_LOGIN_KICKING = 1001,
        RESULT_LOGIN_NOPLAYER = 1002,
        RESULT_LOGIN_OLDVERSION = 1003,
        RESULT_LOGIN_ACCOUNT_LIMIT = 1004,
        RESULT_LOGIN_GET_UIN_ERROR = 1005,
        RESULT_LOGIN_ERROR = 1006,
        RESULT_LOAD_CHARACTER_ERROR = 1007,
        RESULT_LOGIN_NOPLAYERINFO = 1008,
        RESULT_CREATE_ERROR = 1051,
        RESULT_CREATE_ILLEGAL_NAME = 1053,
        RESULT_CREATE_DUPLICATE_NAME = 1054,
        RESULT_ITEM_UNKOWN_ITEM = 1401,
        RESULT_ITEM_EXPIRED_ITEM = 1402,
        RESULT_ITEM_NOT_ENOUGH = 1403,
        RESULT_ACHIEVEMENT_NO_DST = 2301,
        RESULT_ACHIEVEMENT_ERROR_STATUS = 2302,
        RESULT_ACHIEVEMENT_ERROR_TABLE_DATA = 2303,
        RESULT_QUEST_NO_DST = 2401,
        RESULT_QUEST_STATUS_ERROR = 2402,
        RESULT_QUEST_TABLE_ERROR = 2403,
        RESULT_MAIL_NO_DST = 2601,
        RESULT_MAIL_DELETE_FAIL = 2602,
        RESULT_MAIL_READED = 2603,
        RESULT_MAIL_RECEIVED = 2604,
        RESULT_MAIL_TARGET_PLAYER_NOT_FOUND = 2605,
        RESULT_MAIL_EXCESS = 2606,
        RESULT_MAIL_UNREAD = 2607,
        RESULT_CHAT_CD_LIMIT = 2701,
        RESULT_CHAT_IN_USER_BLACKLIST = 2702,
        RESULT_CHAT_IN_SYS_BLACKLIST = 2703,
        RESULT_CHAT_USER_LEVEL_LIMIT = 2704,
        RESULT_CHAT_GUILD_NOT_EXIST = 2705,
        RESULT_CHAT_GROUP_NOT_EXIST = 2706,
        RESULT_CHAT_ITEM_NOT_ENOUGH = 2707,
        RESULT_CHAT_NOT_FOUND_CHANNEL = 2708,
        RESULT_GUILD_ERRNO_SYSERROR = 2801,
        RESULT_GUILD_ERRNO_NAME_LIMIT = 2802,
        RESULT_GUILD_ERRNO_LEADERCANNOTLEAVE = 2803,
        RESULT_GUILD_ERRNO_CANNOTFINDMEMBER = 2804,
        RESULT_GUILD_ERRNO_POSTIONLOW = 2805,
        RESULT_GUILD_ERRNO_GUILDISFULL = 2806,
        RESULT_GUILD_ERRNO_REPEATEDAPPLY = 2807,
        RESULT_GUILD_ERRNO_HASGUILD = 2808,
        RESULT_GUILD_ERRNO_INVITEINVAILD = 2809,
        RESULT_OBJECTIVE_NO_DST = 2901,
        RESULT_OBJECTIVE_STATUS_ERROR = 2902,
        RESULT_OBJECTIVE_TABLE_ERROR = 2903,
        RESULT_RANK_ERROR_ADD_REPEATED = 2950,
        RESULT_RANK_ERROR_ADD_UID = 2951,
        RESULT_RANK_ERROR_ADD_PARAM = 2952,
        RESULT_RANK_ERROR_UID = 2953,
        RESULT_PET_NO_DST = 3500,
        RESULT_FRIEND_FRIENDS_COUNT_MAX = 4201,
        RESULT_FRIEND_FRIENDS_EXIST = 4202,
        RESULT_FRIEND_TARGET_MEMBER_COUNT_MAX = 4203,
        RESULT_FRIEND_TARGET_IS_SELF = 4204,
        RESULT_FRIEND_APPLY_COUNT_MAX = 4205,
        RESULT_FRIEND_APPLY_NOT_EXIST = 4206,
        RESULT_FRIEND_APPLY_IS_EXIST = 4207,
        RESULT_FRIEND_IS_IN_BLACKLIST = 4208,
        RESULT_FRIEND_NOT_IN_BLACKLIST = 4209,
        RESULT_FRIEND_SERVICE_ERROR = 4210,
        RESULT_FRIEND_TCAPLUS_ERROR = 4211,
        RESULT_FRIEND_FRIENDS_INSERT_ERROR = 4212,
        RESULT_FRIEND_FRIENDS_DELETE_ERROR = 4213,
        RESULT_FRIEND_FRIENDS_GET_ERROR = 4214,
        RESULT_FRIEND_APPLY_CHECKBLACK_ERROR = 4215,
        RESULT_FRIEND_APPLY_CHECKAPPLYLIST_ERROR = 4216,
        RESULT_FRIEND_APPLY_REPLY_ERROR = 4217,
        RESULT_FRIEND_APPLY_INSERT_ERROR = 4218,
        RESULT_FRIEND_APPLY_DELETE_ERROR = 4219,
        RESULT_FRIEND_APPLY_GET_ERROR = 4220,
        RESULT_FRIEND_BLACKLIST_INSERT_ERROR = 4221,
        RESULT_FRIEND_BLACKLIST_DELETE_ERROR = 4222,
        RESULT_GM_CMD_NOT_FOUND = 6301,
        RESULT_GM_CMD_NOT_IMPLEMENTED = 6302,
        RESULT_GM_CMD_NOT_HAS_PRIVILEGE = 6303,
        RESULT_RESOURCE_NOT_ENOUGH = 7101,
        RESULT_RESOURCE_WOOD_NOT_ENOUGH = 7102,
        RESULT_RESOURCE_IRON_NOT_ENOUGH = 7103,
        RESULT_RESOURCE_STONE_NOT_ENOUGH = 7104,
        RESULT_RESOURCE_FOOD_NOT_ENOUGH = 7105,
        RESULT_RESOURCE_INK_NOT_ENOUGH = 7106,
        RESULT_RESOURCE_COIN_NOT_ENOUGH = 7107,
        RESULT_RESOURCE_DIAMOND_NOT_ENOUGH = 7108,
        RESULT_RESOURCE_GEMS_NOT_ENOUGH = 7109,
        RESULT_RESOURCE_POINT_NOT_ENOUGH = 7110,
        RESULT_RESOURCE_SP_NOT_ENOUGH = 7111,
        RESULT_RESOURCE_CREDIT_NOT_ENOUGH = 7112,
        RESULT_RESOURCE_DELETE_ITEM_ERROR = 7113,
        RESULT_HERO_FAILED = 7201,
        RESULT_HERO_NOT_FOUND = 7202,
        RESULT_HERO_INVALID = 7203,
        RESULT_HERO_LOCKED = 7204,
        RESULT_HERO_RECYCLE_FAILED = 7205,
        RESULT_CORPS_AVOID_TIME = 7401,
        RESULT_CORPS_STAMINA_NOT_ENOUGH = 7402,
        RESULT_CORPS_COST_NOT_ENOUGH = 7403,
        RESULT_CORPS_REDIF_NOTENOUGH = 7404,
        RESULT_CORPS_NOT_EXIST = 7405,
        RESULT_CORPS_TIRED = 7406,
        RESULT_CORPS_GENERAL_NO_TROOPS = 7407,
        RESULT_CORPS_NOT_AVAILABLE = 7408,
        RESULT_CORPS_TARGET_ARRIVED = 7409,
        RESULT_CORPS_TARGET_UNREACHABLE = 7410,
        RESULT_MAP_POS_INVALID = 7501,
        RESULT_MAP_OWNER_INVALID = 7502,
        RESULT_MAP_BIRTHPOINT_INVALID = 7503,
        RESULT_MAP_DETECT_INVALID = 7511,
        RESULT_MAP_DETECT_CD = 7512,
        RESULT_MAP_DETECT_REPETITION = 7513,
        RESULT_MAP_DETECT_FAILED = 7514,
        RESULT_MAP_REGION_INVALID = 7515,
        RESULT_MAP_REGION_AUTO_OCCUPY_FAILED = 7516,
        RESULT_MAP_BUILDING_NOT_FOUND = 7521,
        RESULT_NOTIFYCATION_INVALID_TID = 8000,
        RESULT_TSS_SERVER_SYSERROR = 8600,
        RESULT_TSS_RESPONSE_DECODE_ERROR = 8601,
        RESULT_TSS_MSGINFO_DECODE_ERROR = 8602,
        RESULT_SHOP_NOT_OPEN = 21101,
        RESULT_SHOP_NOT_FIND = 21102,
        RESULT_SHOP_SOLD_OUT = 21103,
        RESULT_SHOP_NOT_ENOUGH = 21104,
        RESULT_SHOP_SHELF_DATA_NULL = 21105,
        RESULT_SHOP_SHELF_REFRESH_COUNT = 21106,
        RESULT_SHOP_SHELF_REFRESH_TIME = 21107,
        RESULT_SHOP_SHELF_GOOD_DATA_NULL = 21108,
        RESULT_SHOP_SHELF_GOOD_NULL = 21109,
        RESULT_ROOM_TOKEN_ERROR = 21201,
        RESULT_ROOM_LOGIN_ERROR = 21202,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum STORAGE_TYPE
    {
        LOCAL = 0,
        SERVER = 1,
        ALL = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum MAIL_STATUS_TYPE
    {
        UNREAD = 0,
        ITEM_UNREAD = 1,
        READ = 2,
        DELETE = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum MAIL_SENDER_TYPE
    {
        SENDER_TYPE_USER = 0,
        SENDER_TYPE_OPERATION = 1,
        SENDER_TYPE_BACKEND = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum MAIL_RECEIVER_TYPE
    {
        RECEIVER_TYPE_USER = 0,
        RECEIVER_TYPE_GLOBAL = 1,
        RECEIVER_TYPE_GROUP = 2,
        RECEIVER_TYPE_GUILD = 3,
        RECEIVER_GUILD_GROUP = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum CHAT_CHANNEL_TYPE
    {
        CHAT_TYPE_WORLD = 0,
        CHAT_TYPE_GROUP = 1,
        CHAT_TYPE_GUILD = 2,
        CHAT_TYPE_FRIEND = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum StatusOpCode
    {
        Status_None = 0,
        Status_Sync = 1,
        Status_Add = 2,
        Status_Update = 3,
        Status_Remove = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum FriendDataDirtyMark
    {
        MARK_FRIEND_NONE = 0,
        MARK_FRIEND_ADD = 1,
        MARK_FRIEND_DEL = 2,
        MARK_FRIEND_ADD_APPLY = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum SocialDataDirtyMark
    {
        MARK_SOCIAL_NONE = 0,
        MARK_SOCIAL_ENTER_ROOM = 1,
        MARK_FRIEND_STATUS = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ReplyResultCode
    {
        RET_NONE = 0,
        RET_OK = 1,
        RET_REJECT = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum GAME_ERRCODE
    {
        MINIGAME_HANDLE_OK = 0,
        MINIGAME_NO_GAME = 100,
        MINIGAME_INVALID_GAMETID = 101,
        MINIGAME_ILLEGAL_PARAMS = 102,
        MINIGAME_SETTLEMNET_DUPLICATED = 103,
        MINIGAME_INVALID_CONFIG = 104,
        MINIGAME_SCHEDULE_SYSTEM_ERROR = 200,
        MINIGAME_SCHEDULE_NO_WORKER_AVAILABLE = 201,
        MINIGAME_SCHEDULE_GAME_DUPLICATED = 202,
        MINIGAME_SCHEDULE_ERROR_PARAMS = 203,
        MINIGAME_SCHEDULE_CREATE_ROOM = 204,
        MINIGAME_WORKER_SYSTEM_ERROR = 300,
        MINIGAME_WORKER_PARAMS_ERROR = 301,
        MINIGAME_WORKER_GAME_NOT_EXIST = 302,
        MINIGAME_WORKER_PLAYER_NOT_EXIST = 303,
        MINIGAME_WORKER_ENTER_AUTH_FAILED = 304,
        MINIGAME_WORKER_DATA_VERIFY_FAILED = 305,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum GMAE_PLAYER_LEAVE_RULE
    {
        GMAE_PLAYER_LEAVE_RULE_DESTORY = 0,
        GMAE_PLAYER_LEAVE_RULE_KEEP = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ROOM_OPEN_LEVEL
    {
        ROOM_OPEN_LEVEL_NIL = 0,
        ROOM_OPEN_LEVEL_FRIEND = 1,
        ROOM_OPEN_LEVEL_ALL = 10,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ROOM_OWNER_TYPE
    {
        ROOM_OWNER_TYPE_SYSTEM = 0,
        ROOM_OWNER_TYPE_PLAYER = 1,
        ROOM_OWNER_TYPE_SERVER = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ROOM_PRIVILEGE_TYPE
    {
        ROOM_PRIVILEGE_NIL = 0,
        ROOM_PRIVILEGE_REPORT = 1,
        ROOM_PRIVILEGE_BAN = 2,
        ROOM_PRIVILEGE_KICK = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ROOM_TYPE
    {
        ROOM_TYPE_NIL = 0,
        ROOM_TYPE_SYSTEM = 1,
        ROOM_TYPE_GAME = 3,
        ROOM_TYPE_LPL = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum RoomErrorCode
    {
        ROOM_ERRORCODE_NIL = 0,
        ROOM_ERRORCODE_OPENID_NIL = 1,
        ROOM_ERRORCODE_JOIN_UID_ERROR = 4,
        ROOM_ERRORCODE_JOIN_SUBLINE_ERROR = 5,
        ROOM_ERRORCODE_JOIN_TOKEN_ERROR = 6,
        ROOM_ERRORCODE_JOIN_CREATE_PLAYER_ERROR = 7,
        ROOM_ERRORCODE_JOIN_CREATE_PLAYER_SESSION_ERROR = 8,
        ROOM_ERRORCODE_NOT_FIND_PLAYER = 9,
        ROOM_ERRORCODE_NOT_FIND_ROOM = 10,
        ROOM_ERRORCODE_INIT_INITED = 101,
        ROOM_ERRORCODE_PRIVILEGE_NOT_FIND_TARGET = 202,
        ROOM_ERRORCODE_PRIVILEGE_OTHER = 203,
        ROOM_ERRORCODE_VERSION_ERR = 401,
        ROOM_ERRORCODE_ENTITY_MANAGER_ERR = 402,
        ROOM_ERRORCODE_ENTITY_ERR = 403,
        ROOM_ERRORCODE_NO_PRIVILEGE_UPDATE_SETTING = 501,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum PlayerOnlineStatus
    {
        PLAYER_STATUS_ACTIVE = 0,
        PLAYER_STATUS_NOT_ACTIVE = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OculusNotificationType
    {
        OCULUS_NOTIFICATION_NIL = 0,
        OCULUS_NOTIFICATION_INVITE_ROOM = 1,
        OCULUS_NOTIFICATION_APPLY_FRIEND = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OwnerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public OwnerInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public OBJECT_TYPE Type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ItemData()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint Guid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint ItemID { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint Count { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::OpenNGS.Core.NGSAttributes Attributes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ItemList()
        {
            Items = new global::System.Collections.Generic.List<ItemData>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<ItemData> Items { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ItemSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ItemSet()
        {
            Sets = new global::System.Collections.Generic.Dictionary<long, ItemList>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<long, ItemList> Sets { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Queue : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Queue()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public QUEUE_TYPE QueueType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint QueueID { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong Current { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ulong Target { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public float Interval { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public uint StartTime { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public uint RemainTime { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public QUEUE_STATUS Status { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public QUEUE_UPDATE_TYPE UpdateType { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public OwnerInfo Owner { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public ulong Param { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QueueSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public QueueSet()
        {
            Sets = new global::System.Collections.Generic.Dictionary<long, Queue>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<long, Queue> Sets { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestNode : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public QuestNode()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong uid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint groupid { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint questid { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public QUEST_STATE_TYPE status { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public ulong statid { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public ulong curval { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public ulong accepttime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestNodeGroup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public QuestNodeGroup()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint groupid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public QUEST_STATE_TYPE status { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong curval { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TechTree : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public TechTree()
        {
            Items = new global::System.Collections.Generic.Dictionary<long, Tech>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint TreeId { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<long, Tech> Items { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Tech : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Tech()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint Level { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong Queue { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SeasonInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public SeasonInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong total_match { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong win_match { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankRow : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RankRow()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong player_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong score { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public SeasonInfo season_info { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankPage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RankPage()
        {
            rank_rows = new global::System.Collections.Generic.List<RankRow>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<RankRow> rank_rows { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankType : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RankType()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public RANKING_LIFE_TYPE life_type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public RANKING_SCOPE_TYPE scope_type { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public RANK_VALUE_TYPE value_type { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public RANK_ZONE_RANGE_TYPE zone_range { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public ulong zone_id { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public RANK_OBJECT_TYPE object_type { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServiceInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ServiceInfo()
        {
            service_name = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string service_name { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public GetRequest()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong uin { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint count { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint page { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerIdentifier : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PlayerIdentifier()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ListRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ListRequest()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong uin { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint count { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint page { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IdRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public IdRequest()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong uin { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResponseResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ResponseResult()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong errcode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong errmsg { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MailSenderInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MailSenderInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public MAIL_SENDER_TYPE sender_type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong sender_uin { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint sender_guild_position { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ulong sender_guild_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MailReceiverInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MailReceiverInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public MAIL_RECEIVER_TYPE receiver_type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong receiver_uin { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerBaseInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PlayerBaseInfo()
        {
            nickname = "";
            guild_name = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong uin { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nickname { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong guildid { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string guild_name { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerStatusInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PlayerStatusInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong uin { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PLAYER_ONLINE_STATUS_TYPE online_status { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChannelInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ChannelInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public CHAT_CHANNEL_TYPE ctype { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong uid { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong uid1 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChatInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ChatInfo()
        {
            content = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ChannelInfo channel { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string content { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public ulong[] argsparams { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ulong time { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public PlayerBaseInfo sender { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public ulong seq { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MatchPlayerAttribute : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MatchPlayerAttribute()
        {
            name = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong int_val { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MatchPlayer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MatchPlayer()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong uin { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public MatchPlayerAttribute attributes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MatchTicket : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MatchTicket()
        {
            ticket_id = "";
            match_code = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ticket_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong ticket_uid { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string match_code { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public MatchPlayer players { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public ulong begin_time { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public int status { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MatchResultPlayer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MatchResultPlayer()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong uin { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MatchCamp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MatchCamp()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public double score { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public MatchResultPlayer players { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MatchResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MatchResult()
        {
            result_uid = "";
            match_code = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong result_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string result_uid { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string match_code { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ulong create_time { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public MatchCamp camps { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoomStatus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RoomStatus()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong roomTid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong roomUid { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public byte[] token { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public RoomUrl roomurl { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int status { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public ulong maxPlayerLimit { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public ulong uin { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public ROOM_OWNER_TYPE roomOwnerType { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public ROOM_OPEN_LEVEL roomOpenLevel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoomUrl : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RoomUrl()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public byte[] svrService { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong svrInstanceId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong roomTid { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ulong roomUid { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public byte[] token { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoomSetting : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RoomSetting()
        {
            roomName = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string roomName { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint maxPlayerLimit { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ROOM_OPEN_LEVEL roomOpenLevel { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public byte[] metaData { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Vector3 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Vector3()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong x { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong y { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong z { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EntityKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public EntityKey()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong eType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong uid { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong tid { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ulong fatherUid { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public ulong opendId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EntityPos : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public EntityPos()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public Vector3 pos { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Vector3 direction { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong speed { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public Vector3 target { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EntityAttr : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public EntityAttr()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong attrType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong attrId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong value { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public byte[] attrBuf { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Entity : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Entity()
        {
            attrs = new global::System.Collections.Generic.List<EntityAttr>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public EntityKey id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public EntityPos pos { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<EntityAttr> attrs { get; private set; }

        [global::ProtoBuf.ProtoMember(4)]
        public byte[] avatar { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public byte[] attributes { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public uint localid { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public ulong uin { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public ulong hostuin { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public ulong parentuid { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public uint version { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerDesc : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PlayerDesc()
        {
            nickName = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong uin { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nickName { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StatusData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public StatusData()
        {
            SystemName = "";
            Datas = new global::System.Collections.Generic.List<byte[]>();
            Values = new global::System.Collections.Generic.Dictionary<string, ulong>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string SystemName { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public StatusOpCode OpCode { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<byte[]> Datas { get; private set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, ulong> Values { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StatusDataList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public StatusDataList()
        {
            status_datas = new global::System.Collections.Generic.List<StatusData>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<StatusData> status_datas { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DirtyMarkInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public DirtyMarkInfo()
        {
            system_name = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string system_name { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint mark { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RoomData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RoomData()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong owner { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public RoomUrl room_url { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InviteInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public InviteInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong from_uin { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong to_uin { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public RoomData room_info { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ReplyResultCode result { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public ulong timestamp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestEnterInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RequestEnterInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong request_uin { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong be_requested_uin { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public RoomData room_info { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ReplyResultCode result { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public ulong timestamp { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerSocialStatusData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public PlayerSocialStatusData()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong uin { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PlayerStatusInfo status_info { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public RoomData room_info { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserSettingValueItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public UserSettingValueItem()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint value { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public uint[] values { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ObjectiveNode : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public ObjectiveNode()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint groupid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint objid { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public OBJECTIVE_STATE_TYPE status { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ulong curval { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public uint seasonid { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public ulong accepttime { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public ulong endtime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankingKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RankingKey()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public RankingType ObjType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong ObjectId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankingType : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RankingType()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public RANK_ZONE_RANGE_TYPE ZoneRange { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong ZoneId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public RANK_OBJECT_TYPE ObjectType { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public RANK_VALUE_TYPE ValueType { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankingNode : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RankingNode()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public RankingKey RankKey { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong Value { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public RankBaseInfo BaseInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankPlayerBaseInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RankPlayerBaseInfo()
        {
            nickname = "";
            guildname = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong uin { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nickname { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong guildid { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string guildname { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankGuildBaseInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RankGuildBaseInfo()
        {
            guildname = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong guildid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string guildname { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong membernum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RankBaseInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RankBaseInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public RankPlayerBaseInfo player { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public RankGuildBaseInfo guild { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LimitInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public LimitInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint endtime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountIdentity : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public AccountIdentity()
        {
            identity = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public int type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string identity { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AccountInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public AccountInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint gameid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public AccountIdentity identity { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong openid { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ulong permission { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public ulong createtime { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public ulong lastlogintime { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public LimitInfo limit { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public UserInfo()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong userid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong openid { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong serverid { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ulong gentime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CharacterInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public CharacterInfo()
        {
            nickname = "";
            avatar = "";
            imageurl = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong uin { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nickname { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint createtime { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string avatar { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public ulong userid { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public ulong openid { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public LimitInfo limit { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string imageurl { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public AccountIdentity identity { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MiniGameUrl : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MiniGameUrl()
        {
            service_name = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string service_name { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong service_id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong game_tid { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ulong game_uid { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int game_mode { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int game_level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MiniGameLevelData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MiniGameLevelData()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public int level { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int mode { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int status { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long score { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public long time_cost { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public long progress { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public long grade { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MiniGamePlayerData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MiniGamePlayerData()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong uin { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong openid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MiniGameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MiniGameData()
        {
            players = new global::System.Collections.Generic.List<MiniGamePlayerData>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong appid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public MiniGameUrl game_url { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public RoomUrl room_url { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ulong roomtid { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public long create_time { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<MiniGamePlayerData> players { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MiniGameMsgHead : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public MiniGameMsgHead()
        {
            token = "";
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public ulong appid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong gametid { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong gameuid { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string token { get; set; }

    }

}

#pragma warning restore 0612, 0618, 1591, 3021
#endregion
