// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: OpenNGS.Item.Common.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable 0612, 0618, 1591, 3021
namespace OpenNGS.Item.Common
{

    [global::ProtoBuf.ProtoContract()]
    public enum ITEM_CATEGORY
    {
        ITEM_CATEGORY_NONE = 0,
        ITEM_CATEGORY_ITEM = 1,
        ITEM_CATEGORY_RESOURCE = 2,
        ITEM_CATEGORY_PACKAGE = 3,
        ITEM_CATEGORY_BAG = 4,
        ITEM_CATEGORY_CARD = 5,
        ITEM_CATEGORY_AVATAR = 6,
        ITEM_CATEGORY_THEME = 7,
        ITEM_CATEGORY_PET = 8,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ITEM_TYPE
    {
        ITEM_TYPE_NONE = 0,
        ITEM_TYPE_EQUIP_WEAPON = 1,
        ITEM_TYPE_EQUIP_ARMOR = 2,
        ITEM_TYPE_EQUIP_MOUNT = 4,
        ITEM_TYPE_EQUIP_RELICS = 8,
        ITEM_TYPE_EQUIP_ALL = 15,
        ITEM_TYPE_MATERIAL_BLUEPRINT = 256,
        ITEM_TYPE_MATERIAL_STUFF = 512,
        ITEM_TYPE_MATERIAL_ALL = 768,
        ITEM_TYPE_DECORATION = 1024,
        ITEM_TYPE_HANDHELD = 1280,
        ITEM_TYPE_CONSUMABLE = 1536,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ITEM_KIND
    {
        ITEM_KIND_NONE = 0,
        ITEM_KIND_UPPER_CLOTHES = 1,
        ITEM_KIND_LOWER_CLOTHES = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ITEM_EXPIRY_TYPE
    {
        ITEM_EXPIRY_TYPE_NONE = 0,
        ITEM_EXPIRY_TYPE_VALID_TIME = 1,
        ITEM_EXPIRY_TYPE_EXPIRY_TIME = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ITEM_USAGE_TYPE
    {
        ITEM_USAGE_TYPE_NONE = 0,
        ITEM_USAGE_TYPE_USABLE = 1,
        ITEM_USAGE_TYPE_ONE_TIME = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ITEM_PACK_CATEGORY
    {
        ITEM_PACK_CATEGORY_NORMAL = 0,
        ITEM_PACK_CATEGORY_RANDOM = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ITEM_PACK_RANDOM_TYPE
    {
        ITEM_PACK_RANDOM_NORMAL = 0,
        ITEM_PACK_RANDOM_PRD = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ITEM_USE_TIME_TYPE
    {
        ITEM_USE_TIME_TYPE_SINGLE = 0,
        ITEM_USE_TIME_TYPE_MULTIPLE = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ITEM_ATTRIBUTE
    {
        ITEM_ATTRIBUTE_EXP_TIME = 0,
        ITEM_ATTRIBUTE_GET_TIME = 1,
        ITEM_ATTRIBUTE_PLACE_ETERNAL_CNT = 100,
        ITEM_ATTRIBUTE_PLACE_TEMP_CNT = 101,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ITEM_RARITY_TYPE
    {
        ITEM_RARITY_TYPE_NORMAL = 0,
        ITEM_RARITY_TYPE_RARE = 1,
        ITEM_RARITY_TYPE_EPIC = 2,
        ITEM_RARITY_TYPE_LEGENDARY = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ITEM_PLACE_EXPIRATION
    {
        ITEM_PLACE_EXPIRATION_ETERNAL = 0,
        ITEM_PLACE_EXPIRATION_TEMP = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ITEM_PLACE_TYPE
    {
        ITEM_PLACE_TYPE_FORBIDDEN = 0,
        ITEM_PLACE_TYPE_PLACEABLE = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ITEM_VISIBILITY_TYPE
    {
        ITEM_INVISIBLE = 0,
        ITEM_VISIBLE = 1,
    }

}

#pragma warning restore 0612, 0618, 1591, 3021
#endregion
