// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: OpenNGS.Reward.Data.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable 0612, 0618, 1591, 3021
namespace OpenNGS.Reward.Data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Reward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public Reward()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::OpenNGS.Core.NGSText Name { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::OpenNGS.Core.NGSText Desc { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint Condition { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RewardArray : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RewardArray()
        {
            items = new global::System.Collections.Generic.List<Reward>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Reward> items { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RewardContent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RewardContent()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::OpenNGS.Core.NGSText Decs { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint ItemID { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint ItemCount { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public uint Condition { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RewardContentArray : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RewardContentArray()
        {
            items = new global::System.Collections.Generic.List<RewardContent>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<RewardContent> items { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RewardCondition : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RewardCondition()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint ZoneId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint ServerId { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint SeasonId { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public uint ObtainCountLimit { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public uint ValidTime { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RewardConditionArray : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RewardConditionArray()
        {
            items = new global::System.Collections.Generic.List<RewardCondition>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<RewardCondition> items { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RewardData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RewardData()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint ItemID { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint ItemCount { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::OpenNGS.Reward.Common.REWARDSTAT_TYPE Status { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RewardDataArray : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RewardDataArray()
        {
            items = new global::System.Collections.Generic.List<RewardData>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<RewardData> items { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RewardSaveData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RewardSaveData()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint ReceiveCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RewardSaveDataArray : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RewardSaveDataArray()
        {
            items = new global::System.Collections.Generic.List<RewardSaveData>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<RewardSaveData> items { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RewardContainer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RewardContainer()
        {
            rewardDict = new global::System.Collections.Generic.List<RewardSaveData>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<RewardSaveData> rewardDict { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RewardContainerArray : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public RewardContainerArray()
        {
            items = new global::System.Collections.Generic.List<RewardContainer>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<RewardContainer> items { get; private set; }

    }

}

#pragma warning restore 0612, 0618, 1591, 3021
#endregion
