// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: openngs.common.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable 0612, 0618, 1591, 3021
namespace OpenNGS.Common
{

    [global::ProtoBuf.ProtoContract()]
    public enum OBJECT_TYPE
    {
        OBJECT_TYPE_NONE = 0,
        OBJECT_TYPE_PLAYER = 1,
        OBJECT_TYPE_GUILD = 2,
        OBJECT_TYPE_BUILDING = 4,
        OBJECT_TYPE_PET = 8,
        OBJECT_TYPE_CORPS = 16,
        OBJECT_TYPE_TECH = 32,
        OBJECT_TYPE_GLOBAL = 64,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum QUEUE_STATUS
    {
        QUEUE_STATUS_IDLE = 0,
        QUEUE_STATUS_RUNNING = 1,
        QUEUE_STATUS_FINISH = 2,
    }

}

#pragma warning restore 0612, 0618, 1591, 3021
#endregion
