// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openngs.technology.data.proto

#ifndef PROTOBUF_openngs_2etechnology_2edata_2eproto__INCLUDED
#define PROTOBUF_openngs_2etechnology_2edata_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "openngs.core.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_openngs_2etechnology_2edata_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsNodeDataImpl();
void InitDefaultsNodeData();
void InitDefaultsNodeDataArrayImpl();
void InitDefaultsNodeDataArray();
void InitDefaultsTechNodeSaveDataImpl();
void InitDefaultsTechNodeSaveData();
void InitDefaultsTechNodeSaveDataArrayImpl();
void InitDefaultsTechNodeSaveDataArray();
void InitDefaultsTechContainerImpl();
void InitDefaultsTechContainer();
void InitDefaultsTechContainerArrayImpl();
void InitDefaultsTechContainerArray();
inline void InitDefaults() {
  InitDefaultsNodeData();
  InitDefaultsNodeDataArray();
  InitDefaultsTechNodeSaveData();
  InitDefaultsTechNodeSaveDataArray();
  InitDefaultsTechContainer();
  InitDefaultsTechContainerArray();
}
}  // namespace protobuf_openngs_2etechnology_2edata_2eproto
namespace OpenNGS {
namespace Technology {
namespace Data {
class NodeData;
class NodeDataDefaultTypeInternal;
extern NodeDataDefaultTypeInternal _NodeData_default_instance_;
class NodeDataArray;
class NodeDataArrayDefaultTypeInternal;
extern NodeDataArrayDefaultTypeInternal _NodeDataArray_default_instance_;
class TechContainer;
class TechContainerDefaultTypeInternal;
extern TechContainerDefaultTypeInternal _TechContainer_default_instance_;
class TechContainerArray;
class TechContainerArrayDefaultTypeInternal;
extern TechContainerArrayDefaultTypeInternal _TechContainerArray_default_instance_;
class TechNodeSaveData;
class TechNodeSaveDataDefaultTypeInternal;
extern TechNodeSaveDataDefaultTypeInternal _TechNodeSaveData_default_instance_;
class TechNodeSaveDataArray;
class TechNodeSaveDataArrayDefaultTypeInternal;
extern TechNodeSaveDataArrayDefaultTypeInternal _TechNodeSaveDataArray_default_instance_;
}  // namespace Data
}  // namespace Technology
}  // namespace OpenNGS
namespace OpenNGS {
namespace Technology {
namespace Data {

// ===================================================================

class NodeData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:OpenNGS.Technology.Data.NodeData) */ {
 public:
  NodeData();
  virtual ~NodeData();

  NodeData(const NodeData& from);

  inline NodeData& operator=(const NodeData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NodeData(NodeData&& from) noexcept
    : NodeData() {
    *this = ::std::move(from);
  }

  inline NodeData& operator=(NodeData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NodeData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NodeData* internal_default_instance() {
    return reinterpret_cast<const NodeData*>(
               &_NodeData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(NodeData* other);
  friend void swap(NodeData& a, NodeData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NodeData* New() const PROTOBUF_FINAL { return New(NULL); }

  NodeData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NodeData& from);
  void MergeFrom(const NodeData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NodeData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 ChildNodes = 10;
  int childnodes_size() const;
  void clear_childnodes();
  static const int kChildNodesFieldNumber = 10;
  ::google::protobuf::uint32 childnodes(int index) const;
  void set_childnodes(int index, ::google::protobuf::uint32 value);
  void add_childnodes(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      childnodes() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_childnodes();

  // repeated uint32 ParentNode = 11;
  int parentnode_size() const;
  void clear_parentnode();
  static const int kParentNodeFieldNumber = 11;
  ::google::protobuf::uint32 parentnode(int index) const;
  void set_parentnode(int index, ::google::protobuf::uint32 value);
  void add_parentnode(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      parentnode() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_parentnode();

  // repeated float CreatePos = 12;
  int createpos_size() const;
  void clear_createpos();
  static const int kCreatePosFieldNumber = 12;
  float createpos(int index) const;
  void set_createpos(int index, float value);
  void add_createpos(float value);
  const ::google::protobuf::RepeatedField< float >&
      createpos() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_createpos();

  // string Icon = 14;
  void clear_icon();
  static const int kIconFieldNumber = 14;
  const ::std::string& icon() const;
  void set_icon(const ::std::string& value);
  #if LANG_CXX11
  void set_icon(::std::string&& value);
  #endif
  void set_icon(const char* value);
  void set_icon(const char* value, size_t size);
  ::std::string* mutable_icon();
  ::std::string* release_icon();
  void set_allocated_icon(::std::string* icon);

  // .OpenNGS.Core.NGSText Name = 2;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::OpenNGS::Core::NGSText& name() const;
  ::OpenNGS::Core::NGSText* release_name();
  ::OpenNGS::Core::NGSText* mutable_name();
  void set_allocated_name(::OpenNGS::Core::NGSText* name);

  // .OpenNGS.Core.NGSText Description = 7;
  bool has_description() const;
  void clear_description();
  static const int kDescriptionFieldNumber = 7;
  const ::OpenNGS::Core::NGSText& description() const;
  ::OpenNGS::Core::NGSText* release_description();
  ::OpenNGS::Core::NGSText* mutable_description();
  void set_allocated_description(::OpenNGS::Core::NGSText* description);

  // uint32 ID = 1;
  void clear_id();
  static const int kIDFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // uint32 CostItemID = 3;
  void clear_costitemid();
  static const int kCostItemIDFieldNumber = 3;
  ::google::protobuf::uint32 costitemid() const;
  void set_costitemid(::google::protobuf::uint32 value);

  // uint32 CostItemCount = 4;
  void clear_costitemcount();
  static const int kCostItemCountFieldNumber = 4;
  ::google::protobuf::uint32 costitemcount() const;
  void set_costitemcount(::google::protobuf::uint32 value);

  // uint32 Level = 5;
  void clear_level();
  static const int kLevelFieldNumber = 5;
  ::google::protobuf::uint32 level() const;
  void set_level(::google::protobuf::uint32 value);

  // uint32 MaxLevel = 6;
  void clear_maxlevel();
  static const int kMaxLevelFieldNumber = 6;
  ::google::protobuf::uint32 maxlevel() const;
  void set_maxlevel(::google::protobuf::uint32 value);

  // bool Locked = 8;
  void clear_locked();
  static const int kLockedFieldNumber = 8;
  bool locked() const;
  void set_locked(bool value);

  // bool Activated = 9;
  void clear_activated();
  static const int kActivatedFieldNumber = 9;
  bool activated() const;
  void set_activated(bool value);

  // uint32 TreeIndex = 13;
  void clear_treeindex();
  static const int kTreeIndexFieldNumber = 13;
  ::google::protobuf::uint32 treeindex() const;
  void set_treeindex(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:OpenNGS.Technology.Data.NodeData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > childnodes_;
  mutable int _childnodes_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > parentnode_;
  mutable int _parentnode_cached_byte_size_;
  ::google::protobuf::RepeatedField< float > createpos_;
  mutable int _createpos_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr icon_;
  ::OpenNGS::Core::NGSText* name_;
  ::OpenNGS::Core::NGSText* description_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 costitemid_;
  ::google::protobuf::uint32 costitemcount_;
  ::google::protobuf::uint32 level_;
  ::google::protobuf::uint32 maxlevel_;
  bool locked_;
  bool activated_;
  ::google::protobuf::uint32 treeindex_;
  mutable int _cached_size_;
  friend struct ::protobuf_openngs_2etechnology_2edata_2eproto::TableStruct;
  friend void ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsNodeDataImpl();
};
// -------------------------------------------------------------------

class NodeDataArray : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:OpenNGS.Technology.Data.NodeDataArray) */ {
 public:
  NodeDataArray();
  virtual ~NodeDataArray();

  NodeDataArray(const NodeDataArray& from);

  inline NodeDataArray& operator=(const NodeDataArray& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NodeDataArray(NodeDataArray&& from) noexcept
    : NodeDataArray() {
    *this = ::std::move(from);
  }

  inline NodeDataArray& operator=(NodeDataArray&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NodeDataArray& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NodeDataArray* internal_default_instance() {
    return reinterpret_cast<const NodeDataArray*>(
               &_NodeDataArray_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(NodeDataArray* other);
  friend void swap(NodeDataArray& a, NodeDataArray& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NodeDataArray* New() const PROTOBUF_FINAL { return New(NULL); }

  NodeDataArray* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NodeDataArray& from);
  void MergeFrom(const NodeDataArray& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NodeDataArray* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .OpenNGS.Technology.Data.NodeData items = 1;
  int items_size() const;
  void clear_items();
  static const int kItemsFieldNumber = 1;
  const ::OpenNGS::Technology::Data::NodeData& items(int index) const;
  ::OpenNGS::Technology::Data::NodeData* mutable_items(int index);
  ::OpenNGS::Technology::Data::NodeData* add_items();
  ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::NodeData >*
      mutable_items();
  const ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::NodeData >&
      items() const;

  // @@protoc_insertion_point(class_scope:OpenNGS.Technology.Data.NodeDataArray)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::NodeData > items_;
  mutable int _cached_size_;
  friend struct ::protobuf_openngs_2etechnology_2edata_2eproto::TableStruct;
  friend void ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsNodeDataArrayImpl();
};
// -------------------------------------------------------------------

class TechNodeSaveData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:OpenNGS.Technology.Data.TechNodeSaveData) */ {
 public:
  TechNodeSaveData();
  virtual ~TechNodeSaveData();

  TechNodeSaveData(const TechNodeSaveData& from);

  inline TechNodeSaveData& operator=(const TechNodeSaveData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TechNodeSaveData(TechNodeSaveData&& from) noexcept
    : TechNodeSaveData() {
    *this = ::std::move(from);
  }

  inline TechNodeSaveData& operator=(TechNodeSaveData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TechNodeSaveData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TechNodeSaveData* internal_default_instance() {
    return reinterpret_cast<const TechNodeSaveData*>(
               &_TechNodeSaveData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(TechNodeSaveData* other);
  friend void swap(TechNodeSaveData& a, TechNodeSaveData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TechNodeSaveData* New() const PROTOBUF_FINAL { return New(NULL); }

  TechNodeSaveData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TechNodeSaveData& from);
  void MergeFrom(const TechNodeSaveData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TechNodeSaveData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 ID = 1;
  void clear_id();
  static const int kIDFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // uint32 Level = 2;
  void clear_level();
  static const int kLevelFieldNumber = 2;
  ::google::protobuf::uint32 level() const;
  void set_level(::google::protobuf::uint32 value);

  // bool Locked = 3;
  void clear_locked();
  static const int kLockedFieldNumber = 3;
  bool locked() const;
  void set_locked(bool value);

  // bool Activated = 4;
  void clear_activated();
  static const int kActivatedFieldNumber = 4;
  bool activated() const;
  void set_activated(bool value);

  // @@protoc_insertion_point(class_scope:OpenNGS.Technology.Data.TechNodeSaveData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 level_;
  bool locked_;
  bool activated_;
  mutable int _cached_size_;
  friend struct ::protobuf_openngs_2etechnology_2edata_2eproto::TableStruct;
  friend void ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsTechNodeSaveDataImpl();
};
// -------------------------------------------------------------------

class TechNodeSaveDataArray : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:OpenNGS.Technology.Data.TechNodeSaveDataArray) */ {
 public:
  TechNodeSaveDataArray();
  virtual ~TechNodeSaveDataArray();

  TechNodeSaveDataArray(const TechNodeSaveDataArray& from);

  inline TechNodeSaveDataArray& operator=(const TechNodeSaveDataArray& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TechNodeSaveDataArray(TechNodeSaveDataArray&& from) noexcept
    : TechNodeSaveDataArray() {
    *this = ::std::move(from);
  }

  inline TechNodeSaveDataArray& operator=(TechNodeSaveDataArray&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TechNodeSaveDataArray& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TechNodeSaveDataArray* internal_default_instance() {
    return reinterpret_cast<const TechNodeSaveDataArray*>(
               &_TechNodeSaveDataArray_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(TechNodeSaveDataArray* other);
  friend void swap(TechNodeSaveDataArray& a, TechNodeSaveDataArray& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TechNodeSaveDataArray* New() const PROTOBUF_FINAL { return New(NULL); }

  TechNodeSaveDataArray* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TechNodeSaveDataArray& from);
  void MergeFrom(const TechNodeSaveDataArray& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TechNodeSaveDataArray* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .OpenNGS.Technology.Data.TechNodeSaveData items = 1;
  int items_size() const;
  void clear_items();
  static const int kItemsFieldNumber = 1;
  const ::OpenNGS::Technology::Data::TechNodeSaveData& items(int index) const;
  ::OpenNGS::Technology::Data::TechNodeSaveData* mutable_items(int index);
  ::OpenNGS::Technology::Data::TechNodeSaveData* add_items();
  ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::TechNodeSaveData >*
      mutable_items();
  const ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::TechNodeSaveData >&
      items() const;

  // @@protoc_insertion_point(class_scope:OpenNGS.Technology.Data.TechNodeSaveDataArray)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::TechNodeSaveData > items_;
  mutable int _cached_size_;
  friend struct ::protobuf_openngs_2etechnology_2edata_2eproto::TableStruct;
  friend void ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsTechNodeSaveDataArrayImpl();
};
// -------------------------------------------------------------------

class TechContainer : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:OpenNGS.Technology.Data.TechContainer) */ {
 public:
  TechContainer();
  virtual ~TechContainer();

  TechContainer(const TechContainer& from);

  inline TechContainer& operator=(const TechContainer& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TechContainer(TechContainer&& from) noexcept
    : TechContainer() {
    *this = ::std::move(from);
  }

  inline TechContainer& operator=(TechContainer&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TechContainer& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TechContainer* internal_default_instance() {
    return reinterpret_cast<const TechContainer*>(
               &_TechContainer_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(TechContainer* other);
  friend void swap(TechContainer& a, TechContainer& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TechContainer* New() const PROTOBUF_FINAL { return New(NULL); }

  TechContainer* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TechContainer& from);
  void MergeFrom(const TechContainer& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TechContainer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .OpenNGS.Technology.Data.TechNodeSaveData techDict = 1;
  int techdict_size() const;
  void clear_techdict();
  static const int kTechDictFieldNumber = 1;
  const ::OpenNGS::Technology::Data::TechNodeSaveData& techdict(int index) const;
  ::OpenNGS::Technology::Data::TechNodeSaveData* mutable_techdict(int index);
  ::OpenNGS::Technology::Data::TechNodeSaveData* add_techdict();
  ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::TechNodeSaveData >*
      mutable_techdict();
  const ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::TechNodeSaveData >&
      techdict() const;

  // @@protoc_insertion_point(class_scope:OpenNGS.Technology.Data.TechContainer)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::TechNodeSaveData > techdict_;
  mutable int _cached_size_;
  friend struct ::protobuf_openngs_2etechnology_2edata_2eproto::TableStruct;
  friend void ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsTechContainerImpl();
};
// -------------------------------------------------------------------

class TechContainerArray : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:OpenNGS.Technology.Data.TechContainerArray) */ {
 public:
  TechContainerArray();
  virtual ~TechContainerArray();

  TechContainerArray(const TechContainerArray& from);

  inline TechContainerArray& operator=(const TechContainerArray& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TechContainerArray(TechContainerArray&& from) noexcept
    : TechContainerArray() {
    *this = ::std::move(from);
  }

  inline TechContainerArray& operator=(TechContainerArray&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TechContainerArray& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TechContainerArray* internal_default_instance() {
    return reinterpret_cast<const TechContainerArray*>(
               &_TechContainerArray_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(TechContainerArray* other);
  friend void swap(TechContainerArray& a, TechContainerArray& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TechContainerArray* New() const PROTOBUF_FINAL { return New(NULL); }

  TechContainerArray* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TechContainerArray& from);
  void MergeFrom(const TechContainerArray& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TechContainerArray* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .OpenNGS.Technology.Data.TechContainer items = 1;
  int items_size() const;
  void clear_items();
  static const int kItemsFieldNumber = 1;
  const ::OpenNGS::Technology::Data::TechContainer& items(int index) const;
  ::OpenNGS::Technology::Data::TechContainer* mutable_items(int index);
  ::OpenNGS::Technology::Data::TechContainer* add_items();
  ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::TechContainer >*
      mutable_items();
  const ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::TechContainer >&
      items() const;

  // @@protoc_insertion_point(class_scope:OpenNGS.Technology.Data.TechContainerArray)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::TechContainer > items_;
  mutable int _cached_size_;
  friend struct ::protobuf_openngs_2etechnology_2edata_2eproto::TableStruct;
  friend void ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsTechContainerArrayImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NodeData

// uint32 ID = 1;
inline void NodeData::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 NodeData::id() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.NodeData.ID)
  return id_;
}
inline void NodeData::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Technology.Data.NodeData.ID)
}

// .OpenNGS.Core.NGSText Name = 2;
inline bool NodeData::has_name() const {
  return this != internal_default_instance() && name_ != NULL;
}
inline const ::OpenNGS::Core::NGSText& NodeData::name() const {
  const ::OpenNGS::Core::NGSText* p = name_;
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.NodeData.Name)
  return p != NULL ? *p : *reinterpret_cast<const ::OpenNGS::Core::NGSText*>(
      &::OpenNGS::Core::_NGSText_default_instance_);
}
inline ::OpenNGS::Core::NGSText* NodeData::release_name() {
  // @@protoc_insertion_point(field_release:OpenNGS.Technology.Data.NodeData.Name)
  
  ::OpenNGS::Core::NGSText* temp = name_;
  name_ = NULL;
  return temp;
}
inline ::OpenNGS::Core::NGSText* NodeData::mutable_name() {
  
  if (name_ == NULL) {
    name_ = new ::OpenNGS::Core::NGSText;
  }
  // @@protoc_insertion_point(field_mutable:OpenNGS.Technology.Data.NodeData.Name)
  return name_;
}
inline void NodeData::set_allocated_name(::OpenNGS::Core::NGSText* name) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(name_);
  }
  if (name) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      name = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, name, submessage_arena);
    }
    
  } else {
    
  }
  name_ = name;
  // @@protoc_insertion_point(field_set_allocated:OpenNGS.Technology.Data.NodeData.Name)
}

// uint32 CostItemID = 3;
inline void NodeData::clear_costitemid() {
  costitemid_ = 0u;
}
inline ::google::protobuf::uint32 NodeData::costitemid() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.NodeData.CostItemID)
  return costitemid_;
}
inline void NodeData::set_costitemid(::google::protobuf::uint32 value) {
  
  costitemid_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Technology.Data.NodeData.CostItemID)
}

// uint32 CostItemCount = 4;
inline void NodeData::clear_costitemcount() {
  costitemcount_ = 0u;
}
inline ::google::protobuf::uint32 NodeData::costitemcount() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.NodeData.CostItemCount)
  return costitemcount_;
}
inline void NodeData::set_costitemcount(::google::protobuf::uint32 value) {
  
  costitemcount_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Technology.Data.NodeData.CostItemCount)
}

// uint32 Level = 5;
inline void NodeData::clear_level() {
  level_ = 0u;
}
inline ::google::protobuf::uint32 NodeData::level() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.NodeData.Level)
  return level_;
}
inline void NodeData::set_level(::google::protobuf::uint32 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Technology.Data.NodeData.Level)
}

// uint32 MaxLevel = 6;
inline void NodeData::clear_maxlevel() {
  maxlevel_ = 0u;
}
inline ::google::protobuf::uint32 NodeData::maxlevel() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.NodeData.MaxLevel)
  return maxlevel_;
}
inline void NodeData::set_maxlevel(::google::protobuf::uint32 value) {
  
  maxlevel_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Technology.Data.NodeData.MaxLevel)
}

// .OpenNGS.Core.NGSText Description = 7;
inline bool NodeData::has_description() const {
  return this != internal_default_instance() && description_ != NULL;
}
inline const ::OpenNGS::Core::NGSText& NodeData::description() const {
  const ::OpenNGS::Core::NGSText* p = description_;
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.NodeData.Description)
  return p != NULL ? *p : *reinterpret_cast<const ::OpenNGS::Core::NGSText*>(
      &::OpenNGS::Core::_NGSText_default_instance_);
}
inline ::OpenNGS::Core::NGSText* NodeData::release_description() {
  // @@protoc_insertion_point(field_release:OpenNGS.Technology.Data.NodeData.Description)
  
  ::OpenNGS::Core::NGSText* temp = description_;
  description_ = NULL;
  return temp;
}
inline ::OpenNGS::Core::NGSText* NodeData::mutable_description() {
  
  if (description_ == NULL) {
    description_ = new ::OpenNGS::Core::NGSText;
  }
  // @@protoc_insertion_point(field_mutable:OpenNGS.Technology.Data.NodeData.Description)
  return description_;
}
inline void NodeData::set_allocated_description(::OpenNGS::Core::NGSText* description) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(description_);
  }
  if (description) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      description = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, description, submessage_arena);
    }
    
  } else {
    
  }
  description_ = description;
  // @@protoc_insertion_point(field_set_allocated:OpenNGS.Technology.Data.NodeData.Description)
}

// bool Locked = 8;
inline void NodeData::clear_locked() {
  locked_ = false;
}
inline bool NodeData::locked() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.NodeData.Locked)
  return locked_;
}
inline void NodeData::set_locked(bool value) {
  
  locked_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Technology.Data.NodeData.Locked)
}

// bool Activated = 9;
inline void NodeData::clear_activated() {
  activated_ = false;
}
inline bool NodeData::activated() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.NodeData.Activated)
  return activated_;
}
inline void NodeData::set_activated(bool value) {
  
  activated_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Technology.Data.NodeData.Activated)
}

// repeated uint32 ChildNodes = 10;
inline int NodeData::childnodes_size() const {
  return childnodes_.size();
}
inline void NodeData::clear_childnodes() {
  childnodes_.Clear();
}
inline ::google::protobuf::uint32 NodeData::childnodes(int index) const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.NodeData.ChildNodes)
  return childnodes_.Get(index);
}
inline void NodeData::set_childnodes(int index, ::google::protobuf::uint32 value) {
  childnodes_.Set(index, value);
  // @@protoc_insertion_point(field_set:OpenNGS.Technology.Data.NodeData.ChildNodes)
}
inline void NodeData::add_childnodes(::google::protobuf::uint32 value) {
  childnodes_.Add(value);
  // @@protoc_insertion_point(field_add:OpenNGS.Technology.Data.NodeData.ChildNodes)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
NodeData::childnodes() const {
  // @@protoc_insertion_point(field_list:OpenNGS.Technology.Data.NodeData.ChildNodes)
  return childnodes_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
NodeData::mutable_childnodes() {
  // @@protoc_insertion_point(field_mutable_list:OpenNGS.Technology.Data.NodeData.ChildNodes)
  return &childnodes_;
}

// repeated uint32 ParentNode = 11;
inline int NodeData::parentnode_size() const {
  return parentnode_.size();
}
inline void NodeData::clear_parentnode() {
  parentnode_.Clear();
}
inline ::google::protobuf::uint32 NodeData::parentnode(int index) const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.NodeData.ParentNode)
  return parentnode_.Get(index);
}
inline void NodeData::set_parentnode(int index, ::google::protobuf::uint32 value) {
  parentnode_.Set(index, value);
  // @@protoc_insertion_point(field_set:OpenNGS.Technology.Data.NodeData.ParentNode)
}
inline void NodeData::add_parentnode(::google::protobuf::uint32 value) {
  parentnode_.Add(value);
  // @@protoc_insertion_point(field_add:OpenNGS.Technology.Data.NodeData.ParentNode)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
NodeData::parentnode() const {
  // @@protoc_insertion_point(field_list:OpenNGS.Technology.Data.NodeData.ParentNode)
  return parentnode_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
NodeData::mutable_parentnode() {
  // @@protoc_insertion_point(field_mutable_list:OpenNGS.Technology.Data.NodeData.ParentNode)
  return &parentnode_;
}

// repeated float CreatePos = 12;
inline int NodeData::createpos_size() const {
  return createpos_.size();
}
inline void NodeData::clear_createpos() {
  createpos_.Clear();
}
inline float NodeData::createpos(int index) const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.NodeData.CreatePos)
  return createpos_.Get(index);
}
inline void NodeData::set_createpos(int index, float value) {
  createpos_.Set(index, value);
  // @@protoc_insertion_point(field_set:OpenNGS.Technology.Data.NodeData.CreatePos)
}
inline void NodeData::add_createpos(float value) {
  createpos_.Add(value);
  // @@protoc_insertion_point(field_add:OpenNGS.Technology.Data.NodeData.CreatePos)
}
inline const ::google::protobuf::RepeatedField< float >&
NodeData::createpos() const {
  // @@protoc_insertion_point(field_list:OpenNGS.Technology.Data.NodeData.CreatePos)
  return createpos_;
}
inline ::google::protobuf::RepeatedField< float >*
NodeData::mutable_createpos() {
  // @@protoc_insertion_point(field_mutable_list:OpenNGS.Technology.Data.NodeData.CreatePos)
  return &createpos_;
}

// uint32 TreeIndex = 13;
inline void NodeData::clear_treeindex() {
  treeindex_ = 0u;
}
inline ::google::protobuf::uint32 NodeData::treeindex() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.NodeData.TreeIndex)
  return treeindex_;
}
inline void NodeData::set_treeindex(::google::protobuf::uint32 value) {
  
  treeindex_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Technology.Data.NodeData.TreeIndex)
}

// string Icon = 14;
inline void NodeData::clear_icon() {
  icon_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NodeData::icon() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.NodeData.Icon)
  return icon_.GetNoArena();
}
inline void NodeData::set_icon(const ::std::string& value) {
  
  icon_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:OpenNGS.Technology.Data.NodeData.Icon)
}
#if LANG_CXX11
inline void NodeData::set_icon(::std::string&& value) {
  
  icon_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:OpenNGS.Technology.Data.NodeData.Icon)
}
#endif
inline void NodeData::set_icon(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  icon_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:OpenNGS.Technology.Data.NodeData.Icon)
}
inline void NodeData::set_icon(const char* value, size_t size) {
  
  icon_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:OpenNGS.Technology.Data.NodeData.Icon)
}
inline ::std::string* NodeData::mutable_icon() {
  
  // @@protoc_insertion_point(field_mutable:OpenNGS.Technology.Data.NodeData.Icon)
  return icon_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NodeData::release_icon() {
  // @@protoc_insertion_point(field_release:OpenNGS.Technology.Data.NodeData.Icon)
  
  return icon_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NodeData::set_allocated_icon(::std::string* icon) {
  if (icon != NULL) {
    
  } else {
    
  }
  icon_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), icon);
  // @@protoc_insertion_point(field_set_allocated:OpenNGS.Technology.Data.NodeData.Icon)
}

// -------------------------------------------------------------------

// NodeDataArray

// repeated .OpenNGS.Technology.Data.NodeData items = 1;
inline int NodeDataArray::items_size() const {
  return items_.size();
}
inline void NodeDataArray::clear_items() {
  items_.Clear();
}
inline const ::OpenNGS::Technology::Data::NodeData& NodeDataArray::items(int index) const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.NodeDataArray.items)
  return items_.Get(index);
}
inline ::OpenNGS::Technology::Data::NodeData* NodeDataArray::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:OpenNGS.Technology.Data.NodeDataArray.items)
  return items_.Mutable(index);
}
inline ::OpenNGS::Technology::Data::NodeData* NodeDataArray::add_items() {
  // @@protoc_insertion_point(field_add:OpenNGS.Technology.Data.NodeDataArray.items)
  return items_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::NodeData >*
NodeDataArray::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:OpenNGS.Technology.Data.NodeDataArray.items)
  return &items_;
}
inline const ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::NodeData >&
NodeDataArray::items() const {
  // @@protoc_insertion_point(field_list:OpenNGS.Technology.Data.NodeDataArray.items)
  return items_;
}

// -------------------------------------------------------------------

// TechNodeSaveData

// uint32 ID = 1;
inline void TechNodeSaveData::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 TechNodeSaveData::id() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.TechNodeSaveData.ID)
  return id_;
}
inline void TechNodeSaveData::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Technology.Data.TechNodeSaveData.ID)
}

// uint32 Level = 2;
inline void TechNodeSaveData::clear_level() {
  level_ = 0u;
}
inline ::google::protobuf::uint32 TechNodeSaveData::level() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.TechNodeSaveData.Level)
  return level_;
}
inline void TechNodeSaveData::set_level(::google::protobuf::uint32 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Technology.Data.TechNodeSaveData.Level)
}

// bool Locked = 3;
inline void TechNodeSaveData::clear_locked() {
  locked_ = false;
}
inline bool TechNodeSaveData::locked() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.TechNodeSaveData.Locked)
  return locked_;
}
inline void TechNodeSaveData::set_locked(bool value) {
  
  locked_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Technology.Data.TechNodeSaveData.Locked)
}

// bool Activated = 4;
inline void TechNodeSaveData::clear_activated() {
  activated_ = false;
}
inline bool TechNodeSaveData::activated() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.TechNodeSaveData.Activated)
  return activated_;
}
inline void TechNodeSaveData::set_activated(bool value) {
  
  activated_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Technology.Data.TechNodeSaveData.Activated)
}

// -------------------------------------------------------------------

// TechNodeSaveDataArray

// repeated .OpenNGS.Technology.Data.TechNodeSaveData items = 1;
inline int TechNodeSaveDataArray::items_size() const {
  return items_.size();
}
inline void TechNodeSaveDataArray::clear_items() {
  items_.Clear();
}
inline const ::OpenNGS::Technology::Data::TechNodeSaveData& TechNodeSaveDataArray::items(int index) const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.TechNodeSaveDataArray.items)
  return items_.Get(index);
}
inline ::OpenNGS::Technology::Data::TechNodeSaveData* TechNodeSaveDataArray::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:OpenNGS.Technology.Data.TechNodeSaveDataArray.items)
  return items_.Mutable(index);
}
inline ::OpenNGS::Technology::Data::TechNodeSaveData* TechNodeSaveDataArray::add_items() {
  // @@protoc_insertion_point(field_add:OpenNGS.Technology.Data.TechNodeSaveDataArray.items)
  return items_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::TechNodeSaveData >*
TechNodeSaveDataArray::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:OpenNGS.Technology.Data.TechNodeSaveDataArray.items)
  return &items_;
}
inline const ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::TechNodeSaveData >&
TechNodeSaveDataArray::items() const {
  // @@protoc_insertion_point(field_list:OpenNGS.Technology.Data.TechNodeSaveDataArray.items)
  return items_;
}

// -------------------------------------------------------------------

// TechContainer

// repeated .OpenNGS.Technology.Data.TechNodeSaveData techDict = 1;
inline int TechContainer::techdict_size() const {
  return techdict_.size();
}
inline void TechContainer::clear_techdict() {
  techdict_.Clear();
}
inline const ::OpenNGS::Technology::Data::TechNodeSaveData& TechContainer::techdict(int index) const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.TechContainer.techDict)
  return techdict_.Get(index);
}
inline ::OpenNGS::Technology::Data::TechNodeSaveData* TechContainer::mutable_techdict(int index) {
  // @@protoc_insertion_point(field_mutable:OpenNGS.Technology.Data.TechContainer.techDict)
  return techdict_.Mutable(index);
}
inline ::OpenNGS::Technology::Data::TechNodeSaveData* TechContainer::add_techdict() {
  // @@protoc_insertion_point(field_add:OpenNGS.Technology.Data.TechContainer.techDict)
  return techdict_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::TechNodeSaveData >*
TechContainer::mutable_techdict() {
  // @@protoc_insertion_point(field_mutable_list:OpenNGS.Technology.Data.TechContainer.techDict)
  return &techdict_;
}
inline const ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::TechNodeSaveData >&
TechContainer::techdict() const {
  // @@protoc_insertion_point(field_list:OpenNGS.Technology.Data.TechContainer.techDict)
  return techdict_;
}

// -------------------------------------------------------------------

// TechContainerArray

// repeated .OpenNGS.Technology.Data.TechContainer items = 1;
inline int TechContainerArray::items_size() const {
  return items_.size();
}
inline void TechContainerArray::clear_items() {
  items_.Clear();
}
inline const ::OpenNGS::Technology::Data::TechContainer& TechContainerArray::items(int index) const {
  // @@protoc_insertion_point(field_get:OpenNGS.Technology.Data.TechContainerArray.items)
  return items_.Get(index);
}
inline ::OpenNGS::Technology::Data::TechContainer* TechContainerArray::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:OpenNGS.Technology.Data.TechContainerArray.items)
  return items_.Mutable(index);
}
inline ::OpenNGS::Technology::Data::TechContainer* TechContainerArray::add_items() {
  // @@protoc_insertion_point(field_add:OpenNGS.Technology.Data.TechContainerArray.items)
  return items_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::TechContainer >*
TechContainerArray::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:OpenNGS.Technology.Data.TechContainerArray.items)
  return &items_;
}
inline const ::google::protobuf::RepeatedPtrField< ::OpenNGS::Technology::Data::TechContainer >&
TechContainerArray::items() const {
  // @@protoc_insertion_point(field_list:OpenNGS.Technology.Data.TechContainerArray.items)
  return items_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Data
}  // namespace Technology
}  // namespace OpenNGS

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_openngs_2etechnology_2edata_2eproto__INCLUDED
