// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openngs.setting.common.proto

#include "openngs.setting.common.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace OpenNGS {
namespace Setting {
namespace Common {
}  // namespace Common
}  // namespace Setting
}  // namespace OpenNGS
namespace protobuf_openngs_2esetting_2ecommon_2eproto {
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[4];
const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "openngs.setting.common.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      NULL, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

void AddDescriptorsImpl() {
  InitDefaults();
#pragma warning(push)
#pragma warning(disable : 4125)
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\034openngs.setting.common.proto\022\026OpenNGS."
      "Setting.Common*>\n\025RESOLUTIONRATION_TYPE\022"
      "%\n!RESOLUTIONRATION_TYPE_PROGRESSIVE\020\000*g"
      "\n\rLANGUAGE_TYPE\022\024\n\020LANGUAGE_TYPE_ZH\020\000\022\024\n"
      "\020LANGUAGE_TYPE_HK\020\001\022\024\n\020LANGUAGE_TYPE_US\020"
      "\002\022\024\n\020LANGUAGE_TYPE_JM\020\003*T\n\013RESULT_TYPE\022\024"
      "\n\020RESULT_TYPE_NONE\020\000\022\027\n\023RESULT_TYPE_SUCC"
      "ESS\020\001\022\026\n\022RESULT_TYPE_FAILED\020\002*U\n\nADUIO_T"
      "YPE\022\033\n\027ADUIO_TYPE_OVERALLAudio\020\000\022\024\n\020ADUI"
      "O_TYPE_SOUND\020\001\022\024\n\020ADUIO_TYPE_MUSIC\020\002b\006pr"
      "oto3"
  };
#pragma warning(pop)
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 404);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "openngs.setting.common.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_openngs_2esetting_2ecommon_2eproto
namespace OpenNGS {
namespace Setting {
namespace Common {
const ::google::protobuf::EnumDescriptor* RESOLUTIONRATION_TYPE_descriptor() {
  protobuf_openngs_2esetting_2ecommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_openngs_2esetting_2ecommon_2eproto::file_level_enum_descriptors[0];
}
bool RESOLUTIONRATION_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* LANGUAGE_TYPE_descriptor() {
  protobuf_openngs_2esetting_2ecommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_openngs_2esetting_2ecommon_2eproto::file_level_enum_descriptors[1];
}
bool LANGUAGE_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* RESULT_TYPE_descriptor() {
  protobuf_openngs_2esetting_2ecommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_openngs_2esetting_2ecommon_2eproto::file_level_enum_descriptors[2];
}
bool RESULT_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ADUIO_TYPE_descriptor() {
  protobuf_openngs_2esetting_2ecommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_openngs_2esetting_2ecommon_2eproto::file_level_enum_descriptors[3];
}
bool ADUIO_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Common
}  // namespace Setting
}  // namespace OpenNGS

// @@protoc_insertion_point(global_scope)
