// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openngs.message.common.proto

#include "openngs.message.common.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace OpenNGS {
namespace Message {
namespace Common {
}  // namespace Common
}  // namespace Message
}  // namespace OpenNGS
namespace protobuf_openngs_2emessage_2ecommon_2eproto {
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];
const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "openngs.message.common.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      NULL, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

void AddDescriptorsImpl() {
  InitDefaults();
#pragma warning(push)
#pragma warning(disable : 4125)
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\034openngs.message.common.proto\022\026OpenNGS."
      "Message.Common*\205\001\n\013NOTIFY_TYPE\022\024\n\020NOTIFY"
      "_TYPE_NONE\020\000\022\024\n\020NOTIFY_TYPE_TIPS\020\001\022\033\n\027NO"
      "TIFY_TYPE_MESSAGE_BOX\020\002\022\027\n\023NOTIFY_TYPE_M"
      "ARQUEE\020\004\022\024\n\020NOTIFY_TYPE_PUSH\020\010b\006proto3"
  };
#pragma warning(pop)
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 198);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "openngs.message.common.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_openngs_2emessage_2ecommon_2eproto
namespace OpenNGS {
namespace Message {
namespace Common {
const ::google::protobuf::EnumDescriptor* NOTIFY_TYPE_descriptor() {
  protobuf_openngs_2emessage_2ecommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_openngs_2emessage_2ecommon_2eproto::file_level_enum_descriptors[0];
}
bool NOTIFY_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 4:
    case 8:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Common
}  // namespace Message
}  // namespace OpenNGS

// @@protoc_insertion_point(global_scope)
