// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openngs.technology.data.proto

#include "openngs.technology.data.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace OpenNGS {
namespace Technology {
namespace Data {
class NodeDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NodeData>
      _instance;
} _NodeData_default_instance_;
class NodeDataArrayDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NodeDataArray>
      _instance;
} _NodeDataArray_default_instance_;
class TechNodeSaveDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TechNodeSaveData>
      _instance;
} _TechNodeSaveData_default_instance_;
class TechNodeSaveDataArrayDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TechNodeSaveDataArray>
      _instance;
} _TechNodeSaveDataArray_default_instance_;
class TechContainerDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TechContainer>
      _instance;
} _TechContainer_default_instance_;
class TechContainerArrayDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TechContainerArray>
      _instance;
} _TechContainerArray_default_instance_;
}  // namespace Data
}  // namespace Technology
}  // namespace OpenNGS
namespace protobuf_openngs_2etechnology_2edata_2eproto {
void InitDefaultsNodeDataImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_openngs_2ecore_2eproto::InitDefaultsNGSText();
  {
    void* ptr = &::OpenNGS::Technology::Data::_NodeData_default_instance_;
    new (ptr) ::OpenNGS::Technology::Data::NodeData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::OpenNGS::Technology::Data::NodeData::InitAsDefaultInstance();
}

void InitDefaultsNodeData() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsNodeDataImpl);
}

void InitDefaultsNodeDataArrayImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsNodeData();
  {
    void* ptr = &::OpenNGS::Technology::Data::_NodeDataArray_default_instance_;
    new (ptr) ::OpenNGS::Technology::Data::NodeDataArray();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::OpenNGS::Technology::Data::NodeDataArray::InitAsDefaultInstance();
}

void InitDefaultsNodeDataArray() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsNodeDataArrayImpl);
}

void InitDefaultsTechNodeSaveDataImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::OpenNGS::Technology::Data::_TechNodeSaveData_default_instance_;
    new (ptr) ::OpenNGS::Technology::Data::TechNodeSaveData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::OpenNGS::Technology::Data::TechNodeSaveData::InitAsDefaultInstance();
}

void InitDefaultsTechNodeSaveData() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsTechNodeSaveDataImpl);
}

void InitDefaultsTechNodeSaveDataArrayImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsTechNodeSaveData();
  {
    void* ptr = &::OpenNGS::Technology::Data::_TechNodeSaveDataArray_default_instance_;
    new (ptr) ::OpenNGS::Technology::Data::TechNodeSaveDataArray();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::OpenNGS::Technology::Data::TechNodeSaveDataArray::InitAsDefaultInstance();
}

void InitDefaultsTechNodeSaveDataArray() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsTechNodeSaveDataArrayImpl);
}

void InitDefaultsTechContainerImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsTechNodeSaveData();
  {
    void* ptr = &::OpenNGS::Technology::Data::_TechContainer_default_instance_;
    new (ptr) ::OpenNGS::Technology::Data::TechContainer();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::OpenNGS::Technology::Data::TechContainer::InitAsDefaultInstance();
}

void InitDefaultsTechContainer() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsTechContainerImpl);
}

void InitDefaultsTechContainerArrayImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsTechContainer();
  {
    void* ptr = &::OpenNGS::Technology::Data::_TechContainerArray_default_instance_;
    new (ptr) ::OpenNGS::Technology::Data::TechContainerArray();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::OpenNGS::Technology::Data::TechContainerArray::InitAsDefaultInstance();
}

void InitDefaultsTechContainerArray() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsTechContainerArrayImpl);
}

::google::protobuf::Metadata file_level_metadata[6];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::NodeData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::NodeData, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::NodeData, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::NodeData, costitemid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::NodeData, costitemcount_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::NodeData, level_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::NodeData, maxlevel_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::NodeData, description_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::NodeData, locked_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::NodeData, activated_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::NodeData, childnodes_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::NodeData, parentnode_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::NodeData, createpos_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::NodeData, treeindex_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::NodeData, icon_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::NodeDataArray, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::NodeDataArray, items_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::TechNodeSaveData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::TechNodeSaveData, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::TechNodeSaveData, level_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::TechNodeSaveData, locked_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::TechNodeSaveData, activated_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::TechNodeSaveDataArray, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::TechNodeSaveDataArray, items_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::TechContainer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::TechContainer, techdict_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::TechContainerArray, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::OpenNGS::Technology::Data::TechContainerArray, items_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::OpenNGS::Technology::Data::NodeData)},
  { 19, -1, sizeof(::OpenNGS::Technology::Data::NodeDataArray)},
  { 25, -1, sizeof(::OpenNGS::Technology::Data::TechNodeSaveData)},
  { 34, -1, sizeof(::OpenNGS::Technology::Data::TechNodeSaveDataArray)},
  { 40, -1, sizeof(::OpenNGS::Technology::Data::TechContainer)},
  { 46, -1, sizeof(::OpenNGS::Technology::Data::TechContainerArray)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::OpenNGS::Technology::Data::_NodeData_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::OpenNGS::Technology::Data::_NodeDataArray_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::OpenNGS::Technology::Data::_TechNodeSaveData_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::OpenNGS::Technology::Data::_TechNodeSaveDataArray_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::OpenNGS::Technology::Data::_TechContainer_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::OpenNGS::Technology::Data::_TechContainerArray_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "openngs.technology.data.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 6);
}

void AddDescriptorsImpl() {
  InitDefaults();
#pragma warning(push)
#pragma warning(disable : 4125)
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\035openngs.technology.data.proto\022\027OpenNGS"
      ".Technology.Data\032\022openngs.core.proto\"\262\002\n"
      "\010NodeData\022\n\n\002ID\030\001 \001(\r\022#\n\004Name\030\002 \001(\0132\025.Op"
      "enNGS.Core.NGSText\022\022\n\nCostItemID\030\003 \001(\r\022\025"
      "\n\rCostItemCount\030\004 \001(\r\022\r\n\005Level\030\005 \001(\r\022\020\n\010"
      "MaxLevel\030\006 \001(\r\022*\n\013Description\030\007 \001(\0132\025.Op"
      "enNGS.Core.NGSText\022\016\n\006Locked\030\010 \001(\010\022\021\n\tAc"
      "tivated\030\t \001(\010\022\022\n\nChildNodes\030\n \003(\r\022\022\n\nPar"
      "entNode\030\013 \003(\r\022\021\n\tCreatePos\030\014 \003(\002\022\021\n\tTree"
      "Index\030\r \001(\r\022\014\n\004Icon\030\016 \001(\t\"A\n\rNodeDataArr"
      "ay\0220\n\005items\030\001 \003(\0132!.OpenNGS.Technology.D"
      "ata.NodeData\"P\n\020TechNodeSaveData\022\n\n\002ID\030\001"
      " \001(\r\022\r\n\005Level\030\002 \001(\r\022\016\n\006Locked\030\003 \001(\010\022\021\n\tA"
      "ctivated\030\004 \001(\010\"Q\n\025TechNodeSaveDataArray\022"
      "8\n\005items\030\001 \003(\0132).OpenNGS.Technology.Data"
      ".TechNodeSaveData\"L\n\rTechContainer\022;\n\010te"
      "chDict\030\001 \003(\0132).OpenNGS.Technology.Data.T"
      "echNodeSaveData\"K\n\022TechContainerArray\0225\n"
      "\005items\030\001 \003(\0132&.OpenNGS.Technology.Data.T"
      "echContainerb\006proto3"
  };
#pragma warning(pop)
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 780);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "openngs.technology.data.proto", &protobuf_RegisterTypes);
  ::protobuf_openngs_2ecore_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_openngs_2etechnology_2edata_2eproto
namespace OpenNGS {
namespace Technology {
namespace Data {

// ===================================================================

void NodeData::InitAsDefaultInstance() {
  ::OpenNGS::Technology::Data::_NodeData_default_instance_._instance.get_mutable()->name_ = const_cast< ::OpenNGS::Core::NGSText*>(
      ::OpenNGS::Core::NGSText::internal_default_instance());
  ::OpenNGS::Technology::Data::_NodeData_default_instance_._instance.get_mutable()->description_ = const_cast< ::OpenNGS::Core::NGSText*>(
      ::OpenNGS::Core::NGSText::internal_default_instance());
}
void NodeData::clear_name() {
  if (GetArenaNoVirtual() == NULL && name_ != NULL) {
    delete name_;
  }
  name_ = NULL;
}
void NodeData::clear_description() {
  if (GetArenaNoVirtual() == NULL && description_ != NULL) {
    delete description_;
  }
  description_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NodeData::kIDFieldNumber;
const int NodeData::kNameFieldNumber;
const int NodeData::kCostItemIDFieldNumber;
const int NodeData::kCostItemCountFieldNumber;
const int NodeData::kLevelFieldNumber;
const int NodeData::kMaxLevelFieldNumber;
const int NodeData::kDescriptionFieldNumber;
const int NodeData::kLockedFieldNumber;
const int NodeData::kActivatedFieldNumber;
const int NodeData::kChildNodesFieldNumber;
const int NodeData::kParentNodeFieldNumber;
const int NodeData::kCreatePosFieldNumber;
const int NodeData::kTreeIndexFieldNumber;
const int NodeData::kIconFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NodeData::NodeData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsNodeData();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:OpenNGS.Technology.Data.NodeData)
}
NodeData::NodeData(const NodeData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      childnodes_(from.childnodes_),
      parentnode_(from.parentnode_),
      createpos_(from.createpos_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  icon_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.icon().size() > 0) {
    icon_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.icon_);
  }
  if (from.has_name()) {
    name_ = new ::OpenNGS::Core::NGSText(*from.name_);
  } else {
    name_ = NULL;
  }
  if (from.has_description()) {
    description_ = new ::OpenNGS::Core::NGSText(*from.description_);
  } else {
    description_ = NULL;
  }
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&treeindex_) -
    reinterpret_cast<char*>(&id_)) + sizeof(treeindex_));
  // @@protoc_insertion_point(copy_constructor:OpenNGS.Technology.Data.NodeData)
}

void NodeData::SharedCtor() {
  icon_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&name_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&treeindex_) -
      reinterpret_cast<char*>(&name_)) + sizeof(treeindex_));
  _cached_size_ = 0;
}

NodeData::~NodeData() {
  // @@protoc_insertion_point(destructor:OpenNGS.Technology.Data.NodeData)
  SharedDtor();
}

void NodeData::SharedDtor() {
  icon_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete name_;
  if (this != internal_default_instance()) delete description_;
}

void NodeData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NodeData::descriptor() {
  ::protobuf_openngs_2etechnology_2edata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_openngs_2etechnology_2edata_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NodeData& NodeData::default_instance() {
  ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsNodeData();
  return *internal_default_instance();
}

NodeData* NodeData::New(::google::protobuf::Arena* arena) const {
  NodeData* n = new NodeData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void NodeData::Clear() {
// @@protoc_insertion_point(message_clear_start:OpenNGS.Technology.Data.NodeData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  childnodes_.Clear();
  parentnode_.Clear();
  createpos_.Clear();
  icon_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && name_ != NULL) {
    delete name_;
  }
  name_ = NULL;
  if (GetArenaNoVirtual() == NULL && description_ != NULL) {
    delete description_;
  }
  description_ = NULL;
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&treeindex_) -
      reinterpret_cast<char*>(&id_)) + sizeof(treeindex_));
  _internal_metadata_.Clear();
}

bool NodeData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:OpenNGS.Technology.Data.NodeData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 ID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .OpenNGS.Core.NGSText Name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_name()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 CostItemID = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &costitemid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 CostItemCount = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &costitemcount_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 Level = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &level_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 MaxLevel = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &maxlevel_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .OpenNGS.Core.NGSText Description = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_description()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool Locked = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &locked_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool Activated = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &activated_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated uint32 ChildNodes = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_childnodes())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(80u /* 80 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 82u, input, this->mutable_childnodes())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated uint32 ParentNode = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u /* 90 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_parentnode())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(88u /* 88 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 90u, input, this->mutable_parentnode())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float CreatePos = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(98u /* 98 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_createpos())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(101u /* 101 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 98u, input, this->mutable_createpos())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 TreeIndex = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(104u /* 104 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &treeindex_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Icon = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(114u /* 114 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_icon()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->icon().data(), static_cast<int>(this->icon().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "OpenNGS.Technology.Data.NodeData.Icon"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:OpenNGS.Technology.Data.NodeData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:OpenNGS.Technology.Data.NodeData)
  return false;
#undef DO_
}

void NodeData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:OpenNGS.Technology.Data.NodeData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ID = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // .OpenNGS.Core.NGSText Name = 2;
  if (this->has_name()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->name_, output);
  }

  // uint32 CostItemID = 3;
  if (this->costitemid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->costitemid(), output);
  }

  // uint32 CostItemCount = 4;
  if (this->costitemcount() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->costitemcount(), output);
  }

  // uint32 Level = 5;
  if (this->level() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->level(), output);
  }

  // uint32 MaxLevel = 6;
  if (this->maxlevel() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->maxlevel(), output);
  }

  // .OpenNGS.Core.NGSText Description = 7;
  if (this->has_description()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, *this->description_, output);
  }

  // bool Locked = 8;
  if (this->locked() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->locked(), output);
  }

  // bool Activated = 9;
  if (this->activated() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(9, this->activated(), output);
  }

  // repeated uint32 ChildNodes = 10;
  if (this->childnodes_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(10, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _childnodes_cached_byte_size_));
  }
  for (int i = 0, n = this->childnodes_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->childnodes(i), output);
  }

  // repeated uint32 ParentNode = 11;
  if (this->parentnode_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(11, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _parentnode_cached_byte_size_));
  }
  for (int i = 0, n = this->parentnode_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->parentnode(i), output);
  }

  // repeated float CreatePos = 12;
  if (this->createpos_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(12, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _createpos_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->createpos().data(), this->createpos_size(), output);
  }

  // uint32 TreeIndex = 13;
  if (this->treeindex() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(13, this->treeindex(), output);
  }

  // string Icon = 14;
  if (this->icon().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->icon().data(), static_cast<int>(this->icon().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "OpenNGS.Technology.Data.NodeData.Icon");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      14, this->icon(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:OpenNGS.Technology.Data.NodeData)
}

::google::protobuf::uint8* NodeData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:OpenNGS.Technology.Data.NodeData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ID = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // .OpenNGS.Core.NGSText Name = 2;
  if (this->has_name()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, *this->name_, deterministic, target);
  }

  // uint32 CostItemID = 3;
  if (this->costitemid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->costitemid(), target);
  }

  // uint32 CostItemCount = 4;
  if (this->costitemcount() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->costitemcount(), target);
  }

  // uint32 Level = 5;
  if (this->level() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->level(), target);
  }

  // uint32 MaxLevel = 6;
  if (this->maxlevel() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->maxlevel(), target);
  }

  // .OpenNGS.Core.NGSText Description = 7;
  if (this->has_description()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        7, *this->description_, deterministic, target);
  }

  // bool Locked = 8;
  if (this->locked() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->locked(), target);
  }

  // bool Activated = 9;
  if (this->activated() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(9, this->activated(), target);
  }

  // repeated uint32 ChildNodes = 10;
  if (this->childnodes_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      10,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _childnodes_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->childnodes_, target);
  }

  // repeated uint32 ParentNode = 11;
  if (this->parentnode_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      11,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _parentnode_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->parentnode_, target);
  }

  // repeated float CreatePos = 12;
  if (this->createpos_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      12,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _createpos_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->createpos_, target);
  }

  // uint32 TreeIndex = 13;
  if (this->treeindex() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(13, this->treeindex(), target);
  }

  // string Icon = 14;
  if (this->icon().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->icon().data(), static_cast<int>(this->icon().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "OpenNGS.Technology.Data.NodeData.Icon");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        14, this->icon(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OpenNGS.Technology.Data.NodeData)
  return target;
}

size_t NodeData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OpenNGS.Technology.Data.NodeData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated uint32 ChildNodes = 10;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt32Size(this->childnodes_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _childnodes_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated uint32 ParentNode = 11;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt32Size(this->parentnode_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _parentnode_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated float CreatePos = 12;
  {
    unsigned int count = static_cast<unsigned int>(this->createpos_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _createpos_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // string Icon = 14;
  if (this->icon().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->icon());
  }

  // .OpenNGS.Core.NGSText Name = 2;
  if (this->has_name()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->name_);
  }

  // .OpenNGS.Core.NGSText Description = 7;
  if (this->has_description()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->description_);
  }

  // uint32 ID = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->id());
  }

  // uint32 CostItemID = 3;
  if (this->costitemid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->costitemid());
  }

  // uint32 CostItemCount = 4;
  if (this->costitemcount() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->costitemcount());
  }

  // uint32 Level = 5;
  if (this->level() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->level());
  }

  // uint32 MaxLevel = 6;
  if (this->maxlevel() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->maxlevel());
  }

  // bool Locked = 8;
  if (this->locked() != 0) {
    total_size += 1 + 1;
  }

  // bool Activated = 9;
  if (this->activated() != 0) {
    total_size += 1 + 1;
  }

  // uint32 TreeIndex = 13;
  if (this->treeindex() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->treeindex());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NodeData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:OpenNGS.Technology.Data.NodeData)
  GOOGLE_DCHECK_NE(&from, this);
  const NodeData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NodeData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:OpenNGS.Technology.Data.NodeData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:OpenNGS.Technology.Data.NodeData)
    MergeFrom(*source);
  }
}

void NodeData::MergeFrom(const NodeData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OpenNGS.Technology.Data.NodeData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  childnodes_.MergeFrom(from.childnodes_);
  parentnode_.MergeFrom(from.parentnode_);
  createpos_.MergeFrom(from.createpos_);
  if (from.icon().size() > 0) {

    icon_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.icon_);
  }
  if (from.has_name()) {
    mutable_name()->::OpenNGS::Core::NGSText::MergeFrom(from.name());
  }
  if (from.has_description()) {
    mutable_description()->::OpenNGS::Core::NGSText::MergeFrom(from.description());
  }
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.costitemid() != 0) {
    set_costitemid(from.costitemid());
  }
  if (from.costitemcount() != 0) {
    set_costitemcount(from.costitemcount());
  }
  if (from.level() != 0) {
    set_level(from.level());
  }
  if (from.maxlevel() != 0) {
    set_maxlevel(from.maxlevel());
  }
  if (from.locked() != 0) {
    set_locked(from.locked());
  }
  if (from.activated() != 0) {
    set_activated(from.activated());
  }
  if (from.treeindex() != 0) {
    set_treeindex(from.treeindex());
  }
}

void NodeData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:OpenNGS.Technology.Data.NodeData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NodeData::CopyFrom(const NodeData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OpenNGS.Technology.Data.NodeData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NodeData::IsInitialized() const {
  return true;
}

void NodeData::Swap(NodeData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NodeData::InternalSwap(NodeData* other) {
  using std::swap;
  childnodes_.InternalSwap(&other->childnodes_);
  parentnode_.InternalSwap(&other->parentnode_);
  createpos_.InternalSwap(&other->createpos_);
  icon_.Swap(&other->icon_);
  swap(name_, other->name_);
  swap(description_, other->description_);
  swap(id_, other->id_);
  swap(costitemid_, other->costitemid_);
  swap(costitemcount_, other->costitemcount_);
  swap(level_, other->level_);
  swap(maxlevel_, other->maxlevel_);
  swap(locked_, other->locked_);
  swap(activated_, other->activated_);
  swap(treeindex_, other->treeindex_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata NodeData::GetMetadata() const {
  protobuf_openngs_2etechnology_2edata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_openngs_2etechnology_2edata_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void NodeDataArray::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NodeDataArray::kItemsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NodeDataArray::NodeDataArray()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsNodeDataArray();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:OpenNGS.Technology.Data.NodeDataArray)
}
NodeDataArray::NodeDataArray(const NodeDataArray& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      items_(from.items_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:OpenNGS.Technology.Data.NodeDataArray)
}

void NodeDataArray::SharedCtor() {
  _cached_size_ = 0;
}

NodeDataArray::~NodeDataArray() {
  // @@protoc_insertion_point(destructor:OpenNGS.Technology.Data.NodeDataArray)
  SharedDtor();
}

void NodeDataArray::SharedDtor() {
}

void NodeDataArray::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NodeDataArray::descriptor() {
  ::protobuf_openngs_2etechnology_2edata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_openngs_2etechnology_2edata_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NodeDataArray& NodeDataArray::default_instance() {
  ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsNodeDataArray();
  return *internal_default_instance();
}

NodeDataArray* NodeDataArray::New(::google::protobuf::Arena* arena) const {
  NodeDataArray* n = new NodeDataArray;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void NodeDataArray::Clear() {
// @@protoc_insertion_point(message_clear_start:OpenNGS.Technology.Data.NodeDataArray)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  items_.Clear();
  _internal_metadata_.Clear();
}

bool NodeDataArray::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:OpenNGS.Technology.Data.NodeDataArray)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .OpenNGS.Technology.Data.NodeData items = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_items()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:OpenNGS.Technology.Data.NodeDataArray)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:OpenNGS.Technology.Data.NodeDataArray)
  return false;
#undef DO_
}

void NodeDataArray::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:OpenNGS.Technology.Data.NodeDataArray)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .OpenNGS.Technology.Data.NodeData items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->items_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->items(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:OpenNGS.Technology.Data.NodeDataArray)
}

::google::protobuf::uint8* NodeDataArray::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:OpenNGS.Technology.Data.NodeDataArray)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .OpenNGS.Technology.Data.NodeData items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->items_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->items(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OpenNGS.Technology.Data.NodeDataArray)
  return target;
}

size_t NodeDataArray::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OpenNGS.Technology.Data.NodeDataArray)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .OpenNGS.Technology.Data.NodeData items = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->items_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->items(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NodeDataArray::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:OpenNGS.Technology.Data.NodeDataArray)
  GOOGLE_DCHECK_NE(&from, this);
  const NodeDataArray* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NodeDataArray>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:OpenNGS.Technology.Data.NodeDataArray)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:OpenNGS.Technology.Data.NodeDataArray)
    MergeFrom(*source);
  }
}

void NodeDataArray::MergeFrom(const NodeDataArray& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OpenNGS.Technology.Data.NodeDataArray)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  items_.MergeFrom(from.items_);
}

void NodeDataArray::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:OpenNGS.Technology.Data.NodeDataArray)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NodeDataArray::CopyFrom(const NodeDataArray& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OpenNGS.Technology.Data.NodeDataArray)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NodeDataArray::IsInitialized() const {
  return true;
}

void NodeDataArray::Swap(NodeDataArray* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NodeDataArray::InternalSwap(NodeDataArray* other) {
  using std::swap;
  items_.InternalSwap(&other->items_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata NodeDataArray::GetMetadata() const {
  protobuf_openngs_2etechnology_2edata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_openngs_2etechnology_2edata_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void TechNodeSaveData::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TechNodeSaveData::kIDFieldNumber;
const int TechNodeSaveData::kLevelFieldNumber;
const int TechNodeSaveData::kLockedFieldNumber;
const int TechNodeSaveData::kActivatedFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TechNodeSaveData::TechNodeSaveData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsTechNodeSaveData();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:OpenNGS.Technology.Data.TechNodeSaveData)
}
TechNodeSaveData::TechNodeSaveData(const TechNodeSaveData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&activated_) -
    reinterpret_cast<char*>(&id_)) + sizeof(activated_));
  // @@protoc_insertion_point(copy_constructor:OpenNGS.Technology.Data.TechNodeSaveData)
}

void TechNodeSaveData::SharedCtor() {
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&activated_) -
      reinterpret_cast<char*>(&id_)) + sizeof(activated_));
  _cached_size_ = 0;
}

TechNodeSaveData::~TechNodeSaveData() {
  // @@protoc_insertion_point(destructor:OpenNGS.Technology.Data.TechNodeSaveData)
  SharedDtor();
}

void TechNodeSaveData::SharedDtor() {
}

void TechNodeSaveData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TechNodeSaveData::descriptor() {
  ::protobuf_openngs_2etechnology_2edata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_openngs_2etechnology_2edata_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TechNodeSaveData& TechNodeSaveData::default_instance() {
  ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsTechNodeSaveData();
  return *internal_default_instance();
}

TechNodeSaveData* TechNodeSaveData::New(::google::protobuf::Arena* arena) const {
  TechNodeSaveData* n = new TechNodeSaveData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TechNodeSaveData::Clear() {
// @@protoc_insertion_point(message_clear_start:OpenNGS.Technology.Data.TechNodeSaveData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&activated_) -
      reinterpret_cast<char*>(&id_)) + sizeof(activated_));
  _internal_metadata_.Clear();
}

bool TechNodeSaveData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:OpenNGS.Technology.Data.TechNodeSaveData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 ID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 Level = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &level_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool Locked = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &locked_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool Activated = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &activated_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:OpenNGS.Technology.Data.TechNodeSaveData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:OpenNGS.Technology.Data.TechNodeSaveData)
  return false;
#undef DO_
}

void TechNodeSaveData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:OpenNGS.Technology.Data.TechNodeSaveData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ID = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // uint32 Level = 2;
  if (this->level() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->level(), output);
  }

  // bool Locked = 3;
  if (this->locked() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->locked(), output);
  }

  // bool Activated = 4;
  if (this->activated() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->activated(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:OpenNGS.Technology.Data.TechNodeSaveData)
}

::google::protobuf::uint8* TechNodeSaveData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:OpenNGS.Technology.Data.TechNodeSaveData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ID = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // uint32 Level = 2;
  if (this->level() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->level(), target);
  }

  // bool Locked = 3;
  if (this->locked() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->locked(), target);
  }

  // bool Activated = 4;
  if (this->activated() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->activated(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OpenNGS.Technology.Data.TechNodeSaveData)
  return target;
}

size_t TechNodeSaveData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OpenNGS.Technology.Data.TechNodeSaveData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint32 ID = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->id());
  }

  // uint32 Level = 2;
  if (this->level() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->level());
  }

  // bool Locked = 3;
  if (this->locked() != 0) {
    total_size += 1 + 1;
  }

  // bool Activated = 4;
  if (this->activated() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TechNodeSaveData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:OpenNGS.Technology.Data.TechNodeSaveData)
  GOOGLE_DCHECK_NE(&from, this);
  const TechNodeSaveData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TechNodeSaveData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:OpenNGS.Technology.Data.TechNodeSaveData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:OpenNGS.Technology.Data.TechNodeSaveData)
    MergeFrom(*source);
  }
}

void TechNodeSaveData::MergeFrom(const TechNodeSaveData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OpenNGS.Technology.Data.TechNodeSaveData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.level() != 0) {
    set_level(from.level());
  }
  if (from.locked() != 0) {
    set_locked(from.locked());
  }
  if (from.activated() != 0) {
    set_activated(from.activated());
  }
}

void TechNodeSaveData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:OpenNGS.Technology.Data.TechNodeSaveData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TechNodeSaveData::CopyFrom(const TechNodeSaveData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OpenNGS.Technology.Data.TechNodeSaveData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TechNodeSaveData::IsInitialized() const {
  return true;
}

void TechNodeSaveData::Swap(TechNodeSaveData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TechNodeSaveData::InternalSwap(TechNodeSaveData* other) {
  using std::swap;
  swap(id_, other->id_);
  swap(level_, other->level_);
  swap(locked_, other->locked_);
  swap(activated_, other->activated_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TechNodeSaveData::GetMetadata() const {
  protobuf_openngs_2etechnology_2edata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_openngs_2etechnology_2edata_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void TechNodeSaveDataArray::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TechNodeSaveDataArray::kItemsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TechNodeSaveDataArray::TechNodeSaveDataArray()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsTechNodeSaveDataArray();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:OpenNGS.Technology.Data.TechNodeSaveDataArray)
}
TechNodeSaveDataArray::TechNodeSaveDataArray(const TechNodeSaveDataArray& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      items_(from.items_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:OpenNGS.Technology.Data.TechNodeSaveDataArray)
}

void TechNodeSaveDataArray::SharedCtor() {
  _cached_size_ = 0;
}

TechNodeSaveDataArray::~TechNodeSaveDataArray() {
  // @@protoc_insertion_point(destructor:OpenNGS.Technology.Data.TechNodeSaveDataArray)
  SharedDtor();
}

void TechNodeSaveDataArray::SharedDtor() {
}

void TechNodeSaveDataArray::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TechNodeSaveDataArray::descriptor() {
  ::protobuf_openngs_2etechnology_2edata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_openngs_2etechnology_2edata_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TechNodeSaveDataArray& TechNodeSaveDataArray::default_instance() {
  ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsTechNodeSaveDataArray();
  return *internal_default_instance();
}

TechNodeSaveDataArray* TechNodeSaveDataArray::New(::google::protobuf::Arena* arena) const {
  TechNodeSaveDataArray* n = new TechNodeSaveDataArray;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TechNodeSaveDataArray::Clear() {
// @@protoc_insertion_point(message_clear_start:OpenNGS.Technology.Data.TechNodeSaveDataArray)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  items_.Clear();
  _internal_metadata_.Clear();
}

bool TechNodeSaveDataArray::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:OpenNGS.Technology.Data.TechNodeSaveDataArray)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .OpenNGS.Technology.Data.TechNodeSaveData items = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_items()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:OpenNGS.Technology.Data.TechNodeSaveDataArray)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:OpenNGS.Technology.Data.TechNodeSaveDataArray)
  return false;
#undef DO_
}

void TechNodeSaveDataArray::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:OpenNGS.Technology.Data.TechNodeSaveDataArray)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .OpenNGS.Technology.Data.TechNodeSaveData items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->items_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->items(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:OpenNGS.Technology.Data.TechNodeSaveDataArray)
}

::google::protobuf::uint8* TechNodeSaveDataArray::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:OpenNGS.Technology.Data.TechNodeSaveDataArray)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .OpenNGS.Technology.Data.TechNodeSaveData items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->items_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->items(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OpenNGS.Technology.Data.TechNodeSaveDataArray)
  return target;
}

size_t TechNodeSaveDataArray::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OpenNGS.Technology.Data.TechNodeSaveDataArray)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .OpenNGS.Technology.Data.TechNodeSaveData items = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->items_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->items(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TechNodeSaveDataArray::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:OpenNGS.Technology.Data.TechNodeSaveDataArray)
  GOOGLE_DCHECK_NE(&from, this);
  const TechNodeSaveDataArray* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TechNodeSaveDataArray>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:OpenNGS.Technology.Data.TechNodeSaveDataArray)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:OpenNGS.Technology.Data.TechNodeSaveDataArray)
    MergeFrom(*source);
  }
}

void TechNodeSaveDataArray::MergeFrom(const TechNodeSaveDataArray& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OpenNGS.Technology.Data.TechNodeSaveDataArray)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  items_.MergeFrom(from.items_);
}

void TechNodeSaveDataArray::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:OpenNGS.Technology.Data.TechNodeSaveDataArray)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TechNodeSaveDataArray::CopyFrom(const TechNodeSaveDataArray& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OpenNGS.Technology.Data.TechNodeSaveDataArray)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TechNodeSaveDataArray::IsInitialized() const {
  return true;
}

void TechNodeSaveDataArray::Swap(TechNodeSaveDataArray* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TechNodeSaveDataArray::InternalSwap(TechNodeSaveDataArray* other) {
  using std::swap;
  items_.InternalSwap(&other->items_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TechNodeSaveDataArray::GetMetadata() const {
  protobuf_openngs_2etechnology_2edata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_openngs_2etechnology_2edata_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void TechContainer::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TechContainer::kTechDictFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TechContainer::TechContainer()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsTechContainer();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:OpenNGS.Technology.Data.TechContainer)
}
TechContainer::TechContainer(const TechContainer& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      techdict_(from.techdict_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:OpenNGS.Technology.Data.TechContainer)
}

void TechContainer::SharedCtor() {
  _cached_size_ = 0;
}

TechContainer::~TechContainer() {
  // @@protoc_insertion_point(destructor:OpenNGS.Technology.Data.TechContainer)
  SharedDtor();
}

void TechContainer::SharedDtor() {
}

void TechContainer::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TechContainer::descriptor() {
  ::protobuf_openngs_2etechnology_2edata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_openngs_2etechnology_2edata_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TechContainer& TechContainer::default_instance() {
  ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsTechContainer();
  return *internal_default_instance();
}

TechContainer* TechContainer::New(::google::protobuf::Arena* arena) const {
  TechContainer* n = new TechContainer;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TechContainer::Clear() {
// @@protoc_insertion_point(message_clear_start:OpenNGS.Technology.Data.TechContainer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  techdict_.Clear();
  _internal_metadata_.Clear();
}

bool TechContainer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:OpenNGS.Technology.Data.TechContainer)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .OpenNGS.Technology.Data.TechNodeSaveData techDict = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_techdict()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:OpenNGS.Technology.Data.TechContainer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:OpenNGS.Technology.Data.TechContainer)
  return false;
#undef DO_
}

void TechContainer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:OpenNGS.Technology.Data.TechContainer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .OpenNGS.Technology.Data.TechNodeSaveData techDict = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->techdict_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->techdict(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:OpenNGS.Technology.Data.TechContainer)
}

::google::protobuf::uint8* TechContainer::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:OpenNGS.Technology.Data.TechContainer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .OpenNGS.Technology.Data.TechNodeSaveData techDict = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->techdict_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->techdict(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OpenNGS.Technology.Data.TechContainer)
  return target;
}

size_t TechContainer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OpenNGS.Technology.Data.TechContainer)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .OpenNGS.Technology.Data.TechNodeSaveData techDict = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->techdict_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->techdict(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TechContainer::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:OpenNGS.Technology.Data.TechContainer)
  GOOGLE_DCHECK_NE(&from, this);
  const TechContainer* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TechContainer>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:OpenNGS.Technology.Data.TechContainer)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:OpenNGS.Technology.Data.TechContainer)
    MergeFrom(*source);
  }
}

void TechContainer::MergeFrom(const TechContainer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OpenNGS.Technology.Data.TechContainer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  techdict_.MergeFrom(from.techdict_);
}

void TechContainer::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:OpenNGS.Technology.Data.TechContainer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TechContainer::CopyFrom(const TechContainer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OpenNGS.Technology.Data.TechContainer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TechContainer::IsInitialized() const {
  return true;
}

void TechContainer::Swap(TechContainer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TechContainer::InternalSwap(TechContainer* other) {
  using std::swap;
  techdict_.InternalSwap(&other->techdict_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TechContainer::GetMetadata() const {
  protobuf_openngs_2etechnology_2edata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_openngs_2etechnology_2edata_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void TechContainerArray::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TechContainerArray::kItemsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TechContainerArray::TechContainerArray()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsTechContainerArray();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:OpenNGS.Technology.Data.TechContainerArray)
}
TechContainerArray::TechContainerArray(const TechContainerArray& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      items_(from.items_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:OpenNGS.Technology.Data.TechContainerArray)
}

void TechContainerArray::SharedCtor() {
  _cached_size_ = 0;
}

TechContainerArray::~TechContainerArray() {
  // @@protoc_insertion_point(destructor:OpenNGS.Technology.Data.TechContainerArray)
  SharedDtor();
}

void TechContainerArray::SharedDtor() {
}

void TechContainerArray::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TechContainerArray::descriptor() {
  ::protobuf_openngs_2etechnology_2edata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_openngs_2etechnology_2edata_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TechContainerArray& TechContainerArray::default_instance() {
  ::protobuf_openngs_2etechnology_2edata_2eproto::InitDefaultsTechContainerArray();
  return *internal_default_instance();
}

TechContainerArray* TechContainerArray::New(::google::protobuf::Arena* arena) const {
  TechContainerArray* n = new TechContainerArray;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void TechContainerArray::Clear() {
// @@protoc_insertion_point(message_clear_start:OpenNGS.Technology.Data.TechContainerArray)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  items_.Clear();
  _internal_metadata_.Clear();
}

bool TechContainerArray::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:OpenNGS.Technology.Data.TechContainerArray)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .OpenNGS.Technology.Data.TechContainer items = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_items()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:OpenNGS.Technology.Data.TechContainerArray)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:OpenNGS.Technology.Data.TechContainerArray)
  return false;
#undef DO_
}

void TechContainerArray::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:OpenNGS.Technology.Data.TechContainerArray)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .OpenNGS.Technology.Data.TechContainer items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->items_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->items(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:OpenNGS.Technology.Data.TechContainerArray)
}

::google::protobuf::uint8* TechContainerArray::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:OpenNGS.Technology.Data.TechContainerArray)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .OpenNGS.Technology.Data.TechContainer items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->items_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->items(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OpenNGS.Technology.Data.TechContainerArray)
  return target;
}

size_t TechContainerArray::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OpenNGS.Technology.Data.TechContainerArray)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .OpenNGS.Technology.Data.TechContainer items = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->items_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->items(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TechContainerArray::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:OpenNGS.Technology.Data.TechContainerArray)
  GOOGLE_DCHECK_NE(&from, this);
  const TechContainerArray* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TechContainerArray>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:OpenNGS.Technology.Data.TechContainerArray)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:OpenNGS.Technology.Data.TechContainerArray)
    MergeFrom(*source);
  }
}

void TechContainerArray::MergeFrom(const TechContainerArray& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OpenNGS.Technology.Data.TechContainerArray)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  items_.MergeFrom(from.items_);
}

void TechContainerArray::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:OpenNGS.Technology.Data.TechContainerArray)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TechContainerArray::CopyFrom(const TechContainerArray& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OpenNGS.Technology.Data.TechContainerArray)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TechContainerArray::IsInitialized() const {
  return true;
}

void TechContainerArray::Swap(TechContainerArray* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TechContainerArray::InternalSwap(TechContainerArray* other) {
  using std::swap;
  items_.InternalSwap(&other->items_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata TechContainerArray::GetMetadata() const {
  protobuf_openngs_2etechnology_2edata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_openngs_2etechnology_2edata_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Data
}  // namespace Technology
}  // namespace OpenNGS

// @@protoc_insertion_point(global_scope)
