// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openngs.shop.common.proto

#ifndef PROTOBUF_openngs_2eshop_2ecommon_2eproto__INCLUDED
#define PROTOBUF_openngs_2eshop_2ecommon_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace protobuf_openngs_2eshop_2ecommon_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
inline void InitDefaults() {
}
}  // namespace protobuf_openngs_2eshop_2ecommon_2eproto
namespace OpenNGS {
namespace Shop {
namespace Common {
}  // namespace Common
}  // namespace Shop
}  // namespace OpenNGS
namespace OpenNGS {
namespace Shop {
namespace Common {

enum GOOD_TAG_TYPE {
  GOOD_TAG_TYPE_NONE = 0,
  GOOD_TAG_TYPE_NEW = 1,
  GOOD_TAG_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  GOOD_TAG_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool GOOD_TAG_TYPE_IsValid(int value);
const GOOD_TAG_TYPE GOOD_TAG_TYPE_MIN = GOOD_TAG_TYPE_NONE;
const GOOD_TAG_TYPE GOOD_TAG_TYPE_MAX = GOOD_TAG_TYPE_NEW;
const int GOOD_TAG_TYPE_ARRAYSIZE = GOOD_TAG_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* GOOD_TAG_TYPE_descriptor();
inline const ::std::string& GOOD_TAG_TYPE_Name(GOOD_TAG_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    GOOD_TAG_TYPE_descriptor(), value);
}
inline bool GOOD_TAG_TYPE_Parse(
    const ::std::string& name, GOOD_TAG_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GOOD_TAG_TYPE>(
    GOOD_TAG_TYPE_descriptor(), name, value);
}
enum SHELF_STATE_TYPE {
  SHELF_STATE_TYPE_SELL = 0,
  SHELF_STATE_TYPE_OFF__SHELF = 1,
  SHELF_STATE_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  SHELF_STATE_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool SHELF_STATE_TYPE_IsValid(int value);
const SHELF_STATE_TYPE SHELF_STATE_TYPE_MIN = SHELF_STATE_TYPE_SELL;
const SHELF_STATE_TYPE SHELF_STATE_TYPE_MAX = SHELF_STATE_TYPE_OFF__SHELF;
const int SHELF_STATE_TYPE_ARRAYSIZE = SHELF_STATE_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* SHELF_STATE_TYPE_descriptor();
inline const ::std::string& SHELF_STATE_TYPE_Name(SHELF_STATE_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    SHELF_STATE_TYPE_descriptor(), value);
}
inline bool SHELF_STATE_TYPE_Parse(
    const ::std::string& name, SHELF_STATE_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SHELF_STATE_TYPE>(
    SHELF_STATE_TYPE_descriptor(), name, value);
}
enum SHELF_CONDITION_TYPE {
  SHELF_CONDITION_TYPE_NONE = 0,
  SHELF_CONDITION_TYPE_TASK = 1,
  SHELF_CONDITION_TYPE_CONDITION = 2,
  SHELF_CONDITION_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  SHELF_CONDITION_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool SHELF_CONDITION_TYPE_IsValid(int value);
const SHELF_CONDITION_TYPE SHELF_CONDITION_TYPE_MIN = SHELF_CONDITION_TYPE_NONE;
const SHELF_CONDITION_TYPE SHELF_CONDITION_TYPE_MAX = SHELF_CONDITION_TYPE_CONDITION;
const int SHELF_CONDITION_TYPE_ARRAYSIZE = SHELF_CONDITION_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* SHELF_CONDITION_TYPE_descriptor();
inline const ::std::string& SHELF_CONDITION_TYPE_Name(SHELF_CONDITION_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    SHELF_CONDITION_TYPE_descriptor(), value);
}
inline bool SHELF_CONDITION_TYPE_Parse(
    const ::std::string& name, SHELF_CONDITION_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SHELF_CONDITION_TYPE>(
    SHELF_CONDITION_TYPE_descriptor(), name, value);
}
enum SHOP_RESULT_TYPE {
  SHOP_RESULT_TYPE_NONE = 0,
  SHOP_RESULT_TYPE_SUCCESS = 1,
  SHOP_RESULT_TYPE_ERROR_ITEM = 2,
  SHOP_RESULT_TYPE_NO_ITEM = 3,
  SHOP_RESULT_TYPE_NO_SELL = 4,
  SHOP_RESULT_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  SHOP_RESULT_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool SHOP_RESULT_TYPE_IsValid(int value);
const SHOP_RESULT_TYPE SHOP_RESULT_TYPE_MIN = SHOP_RESULT_TYPE_NONE;
const SHOP_RESULT_TYPE SHOP_RESULT_TYPE_MAX = SHOP_RESULT_TYPE_NO_SELL;
const int SHOP_RESULT_TYPE_ARRAYSIZE = SHOP_RESULT_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* SHOP_RESULT_TYPE_descriptor();
inline const ::std::string& SHOP_RESULT_TYPE_Name(SHOP_RESULT_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    SHOP_RESULT_TYPE_descriptor(), value);
}
inline bool SHOP_RESULT_TYPE_Parse(
    const ::std::string& name, SHOP_RESULT_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SHOP_RESULT_TYPE>(
    SHOP_RESULT_TYPE_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Common
}  // namespace Shop
}  // namespace OpenNGS

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::OpenNGS::Shop::Common::GOOD_TAG_TYPE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::OpenNGS::Shop::Common::GOOD_TAG_TYPE>() {
  return ::OpenNGS::Shop::Common::GOOD_TAG_TYPE_descriptor();
}
template <> struct is_proto_enum< ::OpenNGS::Shop::Common::SHELF_STATE_TYPE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::OpenNGS::Shop::Common::SHELF_STATE_TYPE>() {
  return ::OpenNGS::Shop::Common::SHELF_STATE_TYPE_descriptor();
}
template <> struct is_proto_enum< ::OpenNGS::Shop::Common::SHELF_CONDITION_TYPE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::OpenNGS::Shop::Common::SHELF_CONDITION_TYPE>() {
  return ::OpenNGS::Shop::Common::SHELF_CONDITION_TYPE_descriptor();
}
template <> struct is_proto_enum< ::OpenNGS::Shop::Common::SHOP_RESULT_TYPE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::OpenNGS::Shop::Common::SHOP_RESULT_TYPE>() {
  return ::OpenNGS::Shop::Common::SHOP_RESULT_TYPE_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_openngs_2eshop_2ecommon_2eproto__INCLUDED
