// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openngs.statistic.common.proto

#ifndef PROTOBUF_openngs_2estatistic_2ecommon_2eproto__INCLUDED
#define PROTOBUF_openngs_2estatistic_2ecommon_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_openngs_2estatistic_2ecommon_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsStatValueImpl();
void InitDefaultsStatValue();
void InitDefaultsAddStatValueImpl();
void InitDefaultsAddStatValue();
inline void InitDefaults() {
  InitDefaultsStatValue();
  InitDefaultsAddStatValue();
}
}  // namespace protobuf_openngs_2estatistic_2ecommon_2eproto
namespace OpenNGS {
namespace Statistic {
namespace Common {
class AddStatValue;
class AddStatValueDefaultTypeInternal;
extern AddStatValueDefaultTypeInternal _AddStatValue_default_instance_;
class StatValue;
class StatValueDefaultTypeInternal;
extern StatValueDefaultTypeInternal _StatValue_default_instance_;
}  // namespace Common
}  // namespace Statistic
}  // namespace OpenNGS
namespace OpenNGS {
namespace Statistic {
namespace Common {

enum STAT_SYS_TYPE {
  STAT_SYS_TYPE_ALL = 0,
  STAT_SYS_TYPE_ACHIEVEMENT = 1,
  STAT_SYS_TYPE_QUEST = 2,
  STAT_SYS_TYPE_MINIGAME = 3,
  STAT_SYS_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  STAT_SYS_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool STAT_SYS_TYPE_IsValid(int value);
const STAT_SYS_TYPE STAT_SYS_TYPE_MIN = STAT_SYS_TYPE_ALL;
const STAT_SYS_TYPE STAT_SYS_TYPE_MAX = STAT_SYS_TYPE_MINIGAME;
const int STAT_SYS_TYPE_ARRAYSIZE = STAT_SYS_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* STAT_SYS_TYPE_descriptor();
inline const ::std::string& STAT_SYS_TYPE_Name(STAT_SYS_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    STAT_SYS_TYPE_descriptor(), value);
}
inline bool STAT_SYS_TYPE_Parse(
    const ::std::string& name, STAT_SYS_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<STAT_SYS_TYPE>(
    STAT_SYS_TYPE_descriptor(), name, value);
}
enum STAT_COMP_TYPE {
  STAT_COMP_NONE = 0,
  STAT_COMP_GE = 1,
  STAT_COMP_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  STAT_COMP_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool STAT_COMP_TYPE_IsValid(int value);
const STAT_COMP_TYPE STAT_COMP_TYPE_MIN = STAT_COMP_NONE;
const STAT_COMP_TYPE STAT_COMP_TYPE_MAX = STAT_COMP_GE;
const int STAT_COMP_TYPE_ARRAYSIZE = STAT_COMP_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* STAT_COMP_TYPE_descriptor();
inline const ::std::string& STAT_COMP_TYPE_Name(STAT_COMP_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    STAT_COMP_TYPE_descriptor(), value);
}
inline bool STAT_COMP_TYPE_Parse(
    const ::std::string& name, STAT_COMP_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<STAT_COMP_TYPE>(
    STAT_COMP_TYPE_descriptor(), name, value);
}
enum STAT_TYPE {
  STAT_TYPE_CALCULATE_NONE = 0,
  STAT_TYPE_CALCULATE_MAX = 1,
  STAT_TYPE_CALCULATE_MIN = 2,
  STAT_TYPE_CALCULATE_SUM = 3,
  STAT_TYPE_CALCULATE_COUNT = 4,
  STAT_TYPE_CALCULATE_UPDATE = 5,
  STAT_TYPE_CALCULATE_LIST = 6,
  STAT_TYPE_CALCULATE_AVERAGE = 7,
  STAT_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  STAT_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool STAT_TYPE_IsValid(int value);
const STAT_TYPE STAT_TYPE_MIN = STAT_TYPE_CALCULATE_NONE;
const STAT_TYPE STAT_TYPE_MAX = STAT_TYPE_CALCULATE_AVERAGE;
const int STAT_TYPE_ARRAYSIZE = STAT_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* STAT_TYPE_descriptor();
inline const ::std::string& STAT_TYPE_Name(STAT_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    STAT_TYPE_descriptor(), value);
}
inline bool STAT_TYPE_Parse(
    const ::std::string& name, STAT_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<STAT_TYPE>(
    STAT_TYPE_descriptor(), name, value);
}
enum STAT_EVENT {
  STAT_EVENT_NONE = 0,
  STAT_EVENT_USE_ITEM = 1,
  STAT_EVENT_ADD_ITEM = 2,
  STAT_EVENT_SETTLE_MINIGAME = 3,
  STAT_EVENT_LEVEL_TIME = 4,
  STAT_EVENT_KILL_ENEMY_COUNTS = 5,
  STAT_EVENT_UPGRADE_TECH = 6,
  STAT_EVENT_UPGRADE_ITEM = 7,
  STAT_EVENT_COLLECT_SUIT = 8,
  STAT_EVENT_PUZZLE_PLAY = 9,
  STAT_EVENT_PROCESS_MOVEON = 10,
  STAT_EVENT_UI_CLICK = 11,
  STAT_EVENT_LEVEL_GOT_DAMAGE = 12,
  STAT_EVENT_LEVEL_DEATH_COUNTS = 13,
  STAT_EVENT_LEVEL_DAMAGE = 14,
  STAT_EVENT_LEVEL_DAMAGE_PER_SECOND = 15,
  STAT_EVENT_LEVEL_FINISH = 16,
  STAT_EVENT_LEVEL_SURVIVE_TIME = 17,
  STAT_EVENT_LEVEL_KILL_ENEMY = 18,
  STAT_EVENT_LEVEL_PASS_TIME = 19,
  STAT_EVENT_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  STAT_EVENT_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool STAT_EVENT_IsValid(int value);
const STAT_EVENT STAT_EVENT_MIN = STAT_EVENT_NONE;
const STAT_EVENT STAT_EVENT_MAX = STAT_EVENT_LEVEL_PASS_TIME;
const int STAT_EVENT_ARRAYSIZE = STAT_EVENT_MAX + 1;

const ::google::protobuf::EnumDescriptor* STAT_EVENT_descriptor();
inline const ::std::string& STAT_EVENT_Name(STAT_EVENT value) {
  return ::google::protobuf::internal::NameOfEnum(
    STAT_EVENT_descriptor(), value);
}
inline bool STAT_EVENT_Parse(
    const ::std::string& name, STAT_EVENT* value) {
  return ::google::protobuf::internal::ParseNamedEnum<STAT_EVENT>(
    STAT_EVENT_descriptor(), name, value);
}
// ===================================================================

class StatValue : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:OpenNGS.Statistic.Common.StatValue) */ {
 public:
  StatValue();
  virtual ~StatValue();

  StatValue(const StatValue& from);

  inline StatValue& operator=(const StatValue& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StatValue(StatValue&& from) noexcept
    : StatValue() {
    *this = ::std::move(from);
  }

  inline StatValue& operator=(StatValue&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const StatValue& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StatValue* internal_default_instance() {
    return reinterpret_cast<const StatValue*>(
               &_StatValue_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(StatValue* other);
  friend void swap(StatValue& a, StatValue& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StatValue* New() const PROTOBUF_FINAL { return New(NULL); }

  StatValue* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const StatValue& from);
  void MergeFrom(const StatValue& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(StatValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 totalval = 2;
  void clear_totalval();
  static const int kTotalvalFieldNumber = 2;
  ::google::protobuf::uint64 totalval() const;
  void set_totalval(::google::protobuf::uint64 value);

  // uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:OpenNGS.Statistic.Common.StatValue)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 totalval_;
  ::google::protobuf::uint32 id_;
  mutable int _cached_size_;
  friend struct ::protobuf_openngs_2estatistic_2ecommon_2eproto::TableStruct;
  friend void ::protobuf_openngs_2estatistic_2ecommon_2eproto::InitDefaultsStatValueImpl();
};
// -------------------------------------------------------------------

class AddStatValue : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:OpenNGS.Statistic.Common.AddStatValue) */ {
 public:
  AddStatValue();
  virtual ~AddStatValue();

  AddStatValue(const AddStatValue& from);

  inline AddStatValue& operator=(const AddStatValue& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AddStatValue(AddStatValue&& from) noexcept
    : AddStatValue() {
    *this = ::std::move(from);
  }

  inline AddStatValue& operator=(AddStatValue&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AddStatValue& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AddStatValue* internal_default_instance() {
    return reinterpret_cast<const AddStatValue*>(
               &_AddStatValue_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(AddStatValue* other);
  friend void swap(AddStatValue& a, AddStatValue& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AddStatValue* New() const PROTOBUF_FINAL { return New(NULL); }

  AddStatValue* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AddStatValue& from);
  void MergeFrom(const AddStatValue& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AddStatValue* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // uint32 objcategory = 2;
  void clear_objcategory();
  static const int kObjcategoryFieldNumber = 2;
  ::google::protobuf::uint32 objcategory() const;
  void set_objcategory(::google::protobuf::uint32 value);

  // uint64 objtype = 3;
  void clear_objtype();
  static const int kObjtypeFieldNumber = 3;
  ::google::protobuf::uint64 objtype() const;
  void set_objtype(::google::protobuf::uint64 value);

  // uint64 objsubtype = 4;
  void clear_objsubtype();
  static const int kObjsubtypeFieldNumber = 4;
  ::google::protobuf::uint64 objsubtype() const;
  void set_objsubtype(::google::protobuf::uint64 value);

  // uint64 objid = 5;
  void clear_objid();
  static const int kObjidFieldNumber = 5;
  ::google::protobuf::uint64 objid() const;
  void set_objid(::google::protobuf::uint64 value);

  // uint64 val = 6;
  void clear_val();
  static const int kValFieldNumber = 6;
  ::google::protobuf::uint64 val() const;
  void set_val(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:OpenNGS.Statistic.Common.AddStatValue)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 objcategory_;
  ::google::protobuf::uint64 objtype_;
  ::google::protobuf::uint64 objsubtype_;
  ::google::protobuf::uint64 objid_;
  ::google::protobuf::uint64 val_;
  mutable int _cached_size_;
  friend struct ::protobuf_openngs_2estatistic_2ecommon_2eproto::TableStruct;
  friend void ::protobuf_openngs_2estatistic_2ecommon_2eproto::InitDefaultsAddStatValueImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StatValue

// uint32 id = 1;
inline void StatValue::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 StatValue::id() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Statistic.Common.StatValue.id)
  return id_;
}
inline void StatValue::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Statistic.Common.StatValue.id)
}

// uint64 totalval = 2;
inline void StatValue::clear_totalval() {
  totalval_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 StatValue::totalval() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Statistic.Common.StatValue.totalval)
  return totalval_;
}
inline void StatValue::set_totalval(::google::protobuf::uint64 value) {
  
  totalval_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Statistic.Common.StatValue.totalval)
}

// -------------------------------------------------------------------

// AddStatValue

// uint32 id = 1;
inline void AddStatValue::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 AddStatValue::id() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Statistic.Common.AddStatValue.id)
  return id_;
}
inline void AddStatValue::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Statistic.Common.AddStatValue.id)
}

// uint32 objcategory = 2;
inline void AddStatValue::clear_objcategory() {
  objcategory_ = 0u;
}
inline ::google::protobuf::uint32 AddStatValue::objcategory() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Statistic.Common.AddStatValue.objcategory)
  return objcategory_;
}
inline void AddStatValue::set_objcategory(::google::protobuf::uint32 value) {
  
  objcategory_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Statistic.Common.AddStatValue.objcategory)
}

// uint64 objtype = 3;
inline void AddStatValue::clear_objtype() {
  objtype_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 AddStatValue::objtype() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Statistic.Common.AddStatValue.objtype)
  return objtype_;
}
inline void AddStatValue::set_objtype(::google::protobuf::uint64 value) {
  
  objtype_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Statistic.Common.AddStatValue.objtype)
}

// uint64 objsubtype = 4;
inline void AddStatValue::clear_objsubtype() {
  objsubtype_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 AddStatValue::objsubtype() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Statistic.Common.AddStatValue.objsubtype)
  return objsubtype_;
}
inline void AddStatValue::set_objsubtype(::google::protobuf::uint64 value) {
  
  objsubtype_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Statistic.Common.AddStatValue.objsubtype)
}

// uint64 objid = 5;
inline void AddStatValue::clear_objid() {
  objid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 AddStatValue::objid() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Statistic.Common.AddStatValue.objid)
  return objid_;
}
inline void AddStatValue::set_objid(::google::protobuf::uint64 value) {
  
  objid_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Statistic.Common.AddStatValue.objid)
}

// uint64 val = 6;
inline void AddStatValue::clear_val() {
  val_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 AddStatValue::val() const {
  // @@protoc_insertion_point(field_get:OpenNGS.Statistic.Common.AddStatValue.val)
  return val_;
}
inline void AddStatValue::set_val(::google::protobuf::uint64 value) {
  
  val_ = value;
  // @@protoc_insertion_point(field_set:OpenNGS.Statistic.Common.AddStatValue.val)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Common
}  // namespace Statistic
}  // namespace OpenNGS

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::OpenNGS::Statistic::Common::STAT_SYS_TYPE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::OpenNGS::Statistic::Common::STAT_SYS_TYPE>() {
  return ::OpenNGS::Statistic::Common::STAT_SYS_TYPE_descriptor();
}
template <> struct is_proto_enum< ::OpenNGS::Statistic::Common::STAT_COMP_TYPE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::OpenNGS::Statistic::Common::STAT_COMP_TYPE>() {
  return ::OpenNGS::Statistic::Common::STAT_COMP_TYPE_descriptor();
}
template <> struct is_proto_enum< ::OpenNGS::Statistic::Common::STAT_TYPE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::OpenNGS::Statistic::Common::STAT_TYPE>() {
  return ::OpenNGS::Statistic::Common::STAT_TYPE_descriptor();
}
template <> struct is_proto_enum< ::OpenNGS::Statistic::Common::STAT_EVENT> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::OpenNGS::Statistic::Common::STAT_EVENT>() {
  return ::OpenNGS::Statistic::Common::STAT_EVENT_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_openngs_2estatistic_2ecommon_2eproto__INCLUDED
