// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openngs.suit.common.proto

#ifndef PROTOBUF_openngs_2esuit_2ecommon_2eproto__INCLUDED
#define PROTOBUF_openngs_2esuit_2ecommon_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace protobuf_openngs_2esuit_2ecommon_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
inline void InitDefaults() {
}
}  // namespace protobuf_openngs_2esuit_2ecommon_2eproto
namespace OpenNGS {
namespace Suit {
namespace Common {
}  // namespace Common
}  // namespace Suit
}  // namespace OpenNGS
namespace OpenNGS {
namespace Suit {
namespace Common {

enum EQUIP_SUIP_TYPE {
  EQUIP_SUIP_TYPE_THREE = 0,
  EQUIP_SUIP_TYPE_FIVE = 1,
  EQUIP_SUIP_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  EQUIP_SUIP_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool EQUIP_SUIP_TYPE_IsValid(int value);
const EQUIP_SUIP_TYPE EQUIP_SUIP_TYPE_MIN = EQUIP_SUIP_TYPE_THREE;
const EQUIP_SUIP_TYPE EQUIP_SUIP_TYPE_MAX = EQUIP_SUIP_TYPE_FIVE;
const int EQUIP_SUIP_TYPE_ARRAYSIZE = EQUIP_SUIP_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* EQUIP_SUIP_TYPE_descriptor();
inline const ::std::string& EQUIP_SUIP_TYPE_Name(EQUIP_SUIP_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    EQUIP_SUIP_TYPE_descriptor(), value);
}
inline bool EQUIP_SUIP_TYPE_Parse(
    const ::std::string& name, EQUIP_SUIP_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EQUIP_SUIP_TYPE>(
    EQUIP_SUIP_TYPE_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Common
}  // namespace Suit
}  // namespace OpenNGS

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::OpenNGS::Suit::Common::EQUIP_SUIP_TYPE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::OpenNGS::Suit::Common::EQUIP_SUIP_TYPE>() {
  return ::OpenNGS::Suit::Common::EQUIP_SUIP_TYPE_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_openngs_2esuit_2ecommon_2eproto__INCLUDED
