// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openngs.levels.common.proto

#include "openngs.levels.common.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace OpenNGS {
namespace Levels {
namespace Common {
}  // namespace Common
}  // namespace Levels
}  // namespace OpenNGS
namespace protobuf_openngs_2elevels_2ecommon_2eproto {
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[4];
const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "openngs.levels.common.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      NULL, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

void AddDescriptorsImpl() {
  InitDefaults();
#pragma warning(push)
#pragma warning(disable : 4125)
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\033openngs.levels.common.proto\022\025OpenNGS.L"
      "evels.Common*\201\001\n\020LEVEL_STAGE_TYPE\022\031\n\025LEV"
      "EL_STAGE_TYPE_NONE\020\000\022\032\n\026LEVEL_STAGE_TYPE"
      "_BEGIN\020\001\022\034\n\030LEVEL_STAGE_TYPE_PROCESS\020\002\022\030"
      "\n\024LEVEL_STAGE_TYPE_END\020\003*\225\001\n\024STAGE_EXECU"
      "TION_TYPE\022\035\n\031STAGE_EXECUTION_TYPE_NONE\020\000"
      "\022\036\n\032STAGE_EXECUTION_TYPE_BEGIN\020\001\022 \n\034STAG"
      "E_EXECUTION_TYPE_PROCESS\020\002\022\034\n\030STAGE_EXEC"
      "UTION_TYPE_END\020\003*\\\n\016ENEMY_INITTYPE\022\027\n\023EN"
      "EMY_INITTYPE_NONE\020\000\022\030\n\024ENEMY_INITTYPE_RO"
      "UND\020\001\022\027\n\023ENEMY_INITTYPE_AREA\020\002*l\n\021ENEMY_"
      "INITTRIGGER\022\032\n\026ENEMY_INITTRIGGER_NONE\020\000\022"
      "\036\n\032ENEMY_INITTRIGGER_CONSTANT\020\001\022\033\n\027ENEMY"
      "_INITTRIGGER_ENEMY\020\002b\006proto3"
  };
#pragma warning(pop)
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 548);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "openngs.levels.common.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_openngs_2elevels_2ecommon_2eproto
namespace OpenNGS {
namespace Levels {
namespace Common {
const ::google::protobuf::EnumDescriptor* LEVEL_STAGE_TYPE_descriptor() {
  protobuf_openngs_2elevels_2ecommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_openngs_2elevels_2ecommon_2eproto::file_level_enum_descriptors[0];
}
bool LEVEL_STAGE_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* STAGE_EXECUTION_TYPE_descriptor() {
  protobuf_openngs_2elevels_2ecommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_openngs_2elevels_2ecommon_2eproto::file_level_enum_descriptors[1];
}
bool STAGE_EXECUTION_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ENEMY_INITTYPE_descriptor() {
  protobuf_openngs_2elevels_2ecommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_openngs_2elevels_2ecommon_2eproto::file_level_enum_descriptors[2];
}
bool ENEMY_INITTYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* ENEMY_INITTRIGGER_descriptor() {
  protobuf_openngs_2elevels_2ecommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_openngs_2elevels_2ecommon_2eproto::file_level_enum_descriptors[3];
}
bool ENEMY_INITTRIGGER_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Common
}  // namespace Levels
}  // namespace OpenNGS

// @@protoc_insertion_point(global_scope)
