// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openngs.make.common.proto

#ifndef PROTOBUF_openngs_2emake_2ecommon_2eproto__INCLUDED
#define PROTOBUF_openngs_2emake_2ecommon_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace protobuf_openngs_2emake_2ecommon_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
inline void InitDefaults() {
}
}  // namespace protobuf_openngs_2emake_2ecommon_2eproto
namespace OpenNGS {
namespace Make {
namespace Common {
}  // namespace Common
}  // namespace Make
}  // namespace OpenNGS
namespace OpenNGS {
namespace Make {
namespace Common {

enum STATE_TYPE {
  STATE_TYPE_NONE = 0,
  STATE_TYPE_SUCCESS = 1,
  STATE_TYPE_DEFEAT = 2,
  STATE_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  STATE_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool STATE_TYPE_IsValid(int value);
const STATE_TYPE STATE_TYPE_MIN = STATE_TYPE_NONE;
const STATE_TYPE STATE_TYPE_MAX = STATE_TYPE_DEFEAT;
const int STATE_TYPE_ARRAYSIZE = STATE_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* STATE_TYPE_descriptor();
inline const ::std::string& STATE_TYPE_Name(STATE_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    STATE_TYPE_descriptor(), value);
}
inline bool STATE_TYPE_Parse(
    const ::std::string& name, STATE_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<STATE_TYPE>(
    STATE_TYPE_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Common
}  // namespace Make
}  // namespace OpenNGS

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::OpenNGS::Make::Common::STATE_TYPE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::OpenNGS::Make::Common::STATE_TYPE>() {
  return ::OpenNGS::Make::Common::STATE_TYPE_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_openngs_2emake_2ecommon_2eproto__INCLUDED
