// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zerium.data.testdata.proto

#include "zerium.data.testdata.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace Zerium {
namespace Data {
namespace TESTDATA {
class ZeriumDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ZeriumData>
      _instance;
} _ZeriumData_default_instance_;
class ZeriumDataArrayDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ZeriumDataArray>
      _instance;
} _ZeriumDataArray_default_instance_;
class MonsterDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MonsterData>
      _instance;
} _MonsterData_default_instance_;
class MonsterDataArrayDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MonsterDataArray>
      _instance;
} _MonsterDataArray_default_instance_;
}  // namespace TESTDATA
}  // namespace Data
}  // namespace Zerium
namespace protobuf_zerium_2edata_2etestdata_2eproto {
void InitDefaultsZeriumDataImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::Zerium::Data::TESTDATA::_ZeriumData_default_instance_;
    new (ptr) ::Zerium::Data::TESTDATA::ZeriumData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Zerium::Data::TESTDATA::ZeriumData::InitAsDefaultInstance();
}

void InitDefaultsZeriumData() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsZeriumDataImpl);
}

void InitDefaultsZeriumDataArrayImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_zerium_2edata_2etestdata_2eproto::InitDefaultsZeriumData();
  {
    void* ptr = &::Zerium::Data::TESTDATA::_ZeriumDataArray_default_instance_;
    new (ptr) ::Zerium::Data::TESTDATA::ZeriumDataArray();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Zerium::Data::TESTDATA::ZeriumDataArray::InitAsDefaultInstance();
}

void InitDefaultsZeriumDataArray() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsZeriumDataArrayImpl);
}

void InitDefaultsMonsterDataImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::Zerium::Data::TESTDATA::_MonsterData_default_instance_;
    new (ptr) ::Zerium::Data::TESTDATA::MonsterData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Zerium::Data::TESTDATA::MonsterData::InitAsDefaultInstance();
}

void InitDefaultsMonsterData() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsMonsterDataImpl);
}

void InitDefaultsMonsterDataArrayImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_zerium_2edata_2etestdata_2eproto::InitDefaultsMonsterData();
  {
    void* ptr = &::Zerium::Data::TESTDATA::_MonsterDataArray_default_instance_;
    new (ptr) ::Zerium::Data::TESTDATA::MonsterDataArray();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Zerium::Data::TESTDATA::MonsterDataArray::InitAsDefaultInstance();
}

void InitDefaultsMonsterDataArray() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsMonsterDataArrayImpl);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Zerium::Data::TESTDATA::ZeriumData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Zerium::Data::TESTDATA::ZeriumData, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Zerium::Data::TESTDATA::ZeriumData, monstertyp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Zerium::Data::TESTDATA::ZeriumData, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Zerium::Data::TESTDATA::ZeriumData, opentime_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Zerium::Data::TESTDATA::ZeriumData, duration_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Zerium::Data::TESTDATA::ZeriumDataArray, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Zerium::Data::TESTDATA::ZeriumDataArray, items_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Zerium::Data::TESTDATA::MonsterData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Zerium::Data::TESTDATA::MonsterData, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Zerium::Data::TESTDATA::MonsterData, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Zerium::Data::TESTDATA::MonsterData, monsterdesc_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Zerium::Data::TESTDATA::MonsterDataArray, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Zerium::Data::TESTDATA::MonsterDataArray, items_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Zerium::Data::TESTDATA::ZeriumData)},
  { 10, -1, sizeof(::Zerium::Data::TESTDATA::ZeriumDataArray)},
  { 16, -1, sizeof(::Zerium::Data::TESTDATA::MonsterData)},
  { 24, -1, sizeof(::Zerium::Data::TESTDATA::MonsterDataArray)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Zerium::Data::TESTDATA::_ZeriumData_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Zerium::Data::TESTDATA::_ZeriumDataArray_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Zerium::Data::TESTDATA::_MonsterData_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Zerium::Data::TESTDATA::_MonsterDataArray_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "zerium.data.testdata.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
#pragma warning(push)
#pragma warning(disable : 4125)
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\032zerium.data.testdata.proto\022\024Zerium.Dat"
      "a.TESTDATA\032\027zerium.data.enums.proto\"\177\n\nZ"
      "eriumData\022\n\n\002ID\030\001 \001(\r\0223\n\nMonsterTyp\030\002 \001("
      "\0162\037.Zerium.Data.Enums.MONSTER_TYPE\022\014\n\004Na"
      "me\030\003 \001(\t\022\020\n\010OpenTime\030\004 \001(\t\022\020\n\010Duration\030\005"
      " \001(\r\"B\n\017ZeriumDataArray\022/\n\005items\030\001 \003(\0132 "
      ".Zerium.Data.TESTDATA.ZeriumData\"<\n\013Mons"
      "terData\022\n\n\002ID\030\001 \001(\r\022\014\n\004Name\030\002 \001(\t\022\023\n\013Mon"
      "sterDesc\030\003 \001(\t\"D\n\020MonsterDataArray\0220\n\005it"
      "ems\030\001 \003(\0132!.Zerium.Data.TESTDATA.Monster"
      "Datab\006proto3"
  };
#pragma warning(pop)
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 412);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "zerium.data.testdata.proto", &protobuf_RegisterTypes);
  ::protobuf_zerium_2edata_2eenums_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_zerium_2edata_2etestdata_2eproto
namespace Zerium {
namespace Data {
namespace TESTDATA {

// ===================================================================

void ZeriumData::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ZeriumData::kIDFieldNumber;
const int ZeriumData::kMonsterTypFieldNumber;
const int ZeriumData::kNameFieldNumber;
const int ZeriumData::kOpenTimeFieldNumber;
const int ZeriumData::kDurationFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ZeriumData::ZeriumData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_zerium_2edata_2etestdata_2eproto::InitDefaultsZeriumData();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Zerium.Data.TESTDATA.ZeriumData)
}
ZeriumData::ZeriumData(const ZeriumData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  opentime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.opentime().size() > 0) {
    opentime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.opentime_);
  }
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&duration_) -
    reinterpret_cast<char*>(&id_)) + sizeof(duration_));
  // @@protoc_insertion_point(copy_constructor:Zerium.Data.TESTDATA.ZeriumData)
}

void ZeriumData::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  opentime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&duration_) -
      reinterpret_cast<char*>(&id_)) + sizeof(duration_));
  _cached_size_ = 0;
}

ZeriumData::~ZeriumData() {
  // @@protoc_insertion_point(destructor:Zerium.Data.TESTDATA.ZeriumData)
  SharedDtor();
}

void ZeriumData::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  opentime_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ZeriumData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ZeriumData::descriptor() {
  ::protobuf_zerium_2edata_2etestdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_zerium_2edata_2etestdata_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ZeriumData& ZeriumData::default_instance() {
  ::protobuf_zerium_2edata_2etestdata_2eproto::InitDefaultsZeriumData();
  return *internal_default_instance();
}

ZeriumData* ZeriumData::New(::google::protobuf::Arena* arena) const {
  ZeriumData* n = new ZeriumData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ZeriumData::Clear() {
// @@protoc_insertion_point(message_clear_start:Zerium.Data.TESTDATA.ZeriumData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  opentime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&duration_) -
      reinterpret_cast<char*>(&id_)) + sizeof(duration_));
  _internal_metadata_.Clear();
}

bool ZeriumData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Zerium.Data.TESTDATA.ZeriumData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 ID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Zerium.Data.Enums.MONSTER_TYPE MonsterTyp = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_monstertyp(static_cast< ::Zerium::Data::Enums::MONSTER_TYPE >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Name = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Zerium.Data.TESTDATA.ZeriumData.Name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string OpenTime = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_opentime()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->opentime().data(), static_cast<int>(this->opentime().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Zerium.Data.TESTDATA.ZeriumData.OpenTime"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 Duration = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &duration_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Zerium.Data.TESTDATA.ZeriumData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Zerium.Data.TESTDATA.ZeriumData)
  return false;
#undef DO_
}

void ZeriumData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Zerium.Data.TESTDATA.ZeriumData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ID = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // .Zerium.Data.Enums.MONSTER_TYPE MonsterTyp = 2;
  if (this->monstertyp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->monstertyp(), output);
  }

  // string Name = 3;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Zerium.Data.TESTDATA.ZeriumData.Name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->name(), output);
  }

  // string OpenTime = 4;
  if (this->opentime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->opentime().data(), static_cast<int>(this->opentime().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Zerium.Data.TESTDATA.ZeriumData.OpenTime");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->opentime(), output);
  }

  // uint32 Duration = 5;
  if (this->duration() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->duration(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Zerium.Data.TESTDATA.ZeriumData)
}

::google::protobuf::uint8* ZeriumData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Zerium.Data.TESTDATA.ZeriumData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ID = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // .Zerium.Data.Enums.MONSTER_TYPE MonsterTyp = 2;
  if (this->monstertyp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->monstertyp(), target);
  }

  // string Name = 3;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Zerium.Data.TESTDATA.ZeriumData.Name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->name(), target);
  }

  // string OpenTime = 4;
  if (this->opentime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->opentime().data(), static_cast<int>(this->opentime().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Zerium.Data.TESTDATA.ZeriumData.OpenTime");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->opentime(), target);
  }

  // uint32 Duration = 5;
  if (this->duration() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->duration(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Zerium.Data.TESTDATA.ZeriumData)
  return target;
}

size_t ZeriumData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Zerium.Data.TESTDATA.ZeriumData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string Name = 3;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string OpenTime = 4;
  if (this->opentime().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->opentime());
  }

  // uint32 ID = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->id());
  }

  // .Zerium.Data.Enums.MONSTER_TYPE MonsterTyp = 2;
  if (this->monstertyp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->monstertyp());
  }

  // uint32 Duration = 5;
  if (this->duration() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->duration());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ZeriumData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Zerium.Data.TESTDATA.ZeriumData)
  GOOGLE_DCHECK_NE(&from, this);
  const ZeriumData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ZeriumData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Zerium.Data.TESTDATA.ZeriumData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Zerium.Data.TESTDATA.ZeriumData)
    MergeFrom(*source);
  }
}

void ZeriumData::MergeFrom(const ZeriumData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Zerium.Data.TESTDATA.ZeriumData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.opentime().size() > 0) {

    opentime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.opentime_);
  }
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.monstertyp() != 0) {
    set_monstertyp(from.monstertyp());
  }
  if (from.duration() != 0) {
    set_duration(from.duration());
  }
}

void ZeriumData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Zerium.Data.TESTDATA.ZeriumData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ZeriumData::CopyFrom(const ZeriumData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Zerium.Data.TESTDATA.ZeriumData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ZeriumData::IsInitialized() const {
  return true;
}

void ZeriumData::Swap(ZeriumData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ZeriumData::InternalSwap(ZeriumData* other) {
  using std::swap;
  name_.Swap(&other->name_);
  opentime_.Swap(&other->opentime_);
  swap(id_, other->id_);
  swap(monstertyp_, other->monstertyp_);
  swap(duration_, other->duration_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ZeriumData::GetMetadata() const {
  protobuf_zerium_2edata_2etestdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_zerium_2edata_2etestdata_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ZeriumDataArray::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ZeriumDataArray::kItemsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ZeriumDataArray::ZeriumDataArray()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_zerium_2edata_2etestdata_2eproto::InitDefaultsZeriumDataArray();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Zerium.Data.TESTDATA.ZeriumDataArray)
}
ZeriumDataArray::ZeriumDataArray(const ZeriumDataArray& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      items_(from.items_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Zerium.Data.TESTDATA.ZeriumDataArray)
}

void ZeriumDataArray::SharedCtor() {
  _cached_size_ = 0;
}

ZeriumDataArray::~ZeriumDataArray() {
  // @@protoc_insertion_point(destructor:Zerium.Data.TESTDATA.ZeriumDataArray)
  SharedDtor();
}

void ZeriumDataArray::SharedDtor() {
}

void ZeriumDataArray::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ZeriumDataArray::descriptor() {
  ::protobuf_zerium_2edata_2etestdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_zerium_2edata_2etestdata_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ZeriumDataArray& ZeriumDataArray::default_instance() {
  ::protobuf_zerium_2edata_2etestdata_2eproto::InitDefaultsZeriumDataArray();
  return *internal_default_instance();
}

ZeriumDataArray* ZeriumDataArray::New(::google::protobuf::Arena* arena) const {
  ZeriumDataArray* n = new ZeriumDataArray;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ZeriumDataArray::Clear() {
// @@protoc_insertion_point(message_clear_start:Zerium.Data.TESTDATA.ZeriumDataArray)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  items_.Clear();
  _internal_metadata_.Clear();
}

bool ZeriumDataArray::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Zerium.Data.TESTDATA.ZeriumDataArray)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .Zerium.Data.TESTDATA.ZeriumData items = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_items()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Zerium.Data.TESTDATA.ZeriumDataArray)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Zerium.Data.TESTDATA.ZeriumDataArray)
  return false;
#undef DO_
}

void ZeriumDataArray::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Zerium.Data.TESTDATA.ZeriumDataArray)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Zerium.Data.TESTDATA.ZeriumData items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->items_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->items(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Zerium.Data.TESTDATA.ZeriumDataArray)
}

::google::protobuf::uint8* ZeriumDataArray::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Zerium.Data.TESTDATA.ZeriumDataArray)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Zerium.Data.TESTDATA.ZeriumData items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->items_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->items(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Zerium.Data.TESTDATA.ZeriumDataArray)
  return target;
}

size_t ZeriumDataArray::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Zerium.Data.TESTDATA.ZeriumDataArray)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .Zerium.Data.TESTDATA.ZeriumData items = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->items_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->items(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ZeriumDataArray::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Zerium.Data.TESTDATA.ZeriumDataArray)
  GOOGLE_DCHECK_NE(&from, this);
  const ZeriumDataArray* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ZeriumDataArray>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Zerium.Data.TESTDATA.ZeriumDataArray)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Zerium.Data.TESTDATA.ZeriumDataArray)
    MergeFrom(*source);
  }
}

void ZeriumDataArray::MergeFrom(const ZeriumDataArray& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Zerium.Data.TESTDATA.ZeriumDataArray)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  items_.MergeFrom(from.items_);
}

void ZeriumDataArray::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Zerium.Data.TESTDATA.ZeriumDataArray)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ZeriumDataArray::CopyFrom(const ZeriumDataArray& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Zerium.Data.TESTDATA.ZeriumDataArray)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ZeriumDataArray::IsInitialized() const {
  return true;
}

void ZeriumDataArray::Swap(ZeriumDataArray* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ZeriumDataArray::InternalSwap(ZeriumDataArray* other) {
  using std::swap;
  items_.InternalSwap(&other->items_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ZeriumDataArray::GetMetadata() const {
  protobuf_zerium_2edata_2etestdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_zerium_2edata_2etestdata_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MonsterData::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MonsterData::kIDFieldNumber;
const int MonsterData::kNameFieldNumber;
const int MonsterData::kMonsterDescFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MonsterData::MonsterData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_zerium_2edata_2etestdata_2eproto::InitDefaultsMonsterData();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Zerium.Data.TESTDATA.MonsterData)
}
MonsterData::MonsterData(const MonsterData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  monsterdesc_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.monsterdesc().size() > 0) {
    monsterdesc_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.monsterdesc_);
  }
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:Zerium.Data.TESTDATA.MonsterData)
}

void MonsterData::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  monsterdesc_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = 0u;
  _cached_size_ = 0;
}

MonsterData::~MonsterData() {
  // @@protoc_insertion_point(destructor:Zerium.Data.TESTDATA.MonsterData)
  SharedDtor();
}

void MonsterData::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  monsterdesc_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void MonsterData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MonsterData::descriptor() {
  ::protobuf_zerium_2edata_2etestdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_zerium_2edata_2etestdata_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MonsterData& MonsterData::default_instance() {
  ::protobuf_zerium_2edata_2etestdata_2eproto::InitDefaultsMonsterData();
  return *internal_default_instance();
}

MonsterData* MonsterData::New(::google::protobuf::Arena* arena) const {
  MonsterData* n = new MonsterData;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MonsterData::Clear() {
// @@protoc_insertion_point(message_clear_start:Zerium.Data.TESTDATA.MonsterData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  monsterdesc_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = 0u;
  _internal_metadata_.Clear();
}

bool MonsterData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Zerium.Data.TESTDATA.MonsterData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 ID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Zerium.Data.TESTDATA.MonsterData.Name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string MonsterDesc = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_monsterdesc()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->monsterdesc().data(), static_cast<int>(this->monsterdesc().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Zerium.Data.TESTDATA.MonsterData.MonsterDesc"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Zerium.Data.TESTDATA.MonsterData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Zerium.Data.TESTDATA.MonsterData)
  return false;
#undef DO_
}

void MonsterData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Zerium.Data.TESTDATA.MonsterData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ID = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // string Name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Zerium.Data.TESTDATA.MonsterData.Name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  // string MonsterDesc = 3;
  if (this->monsterdesc().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->monsterdesc().data(), static_cast<int>(this->monsterdesc().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Zerium.Data.TESTDATA.MonsterData.MonsterDesc");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->monsterdesc(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Zerium.Data.TESTDATA.MonsterData)
}

::google::protobuf::uint8* MonsterData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Zerium.Data.TESTDATA.MonsterData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ID = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // string Name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Zerium.Data.TESTDATA.MonsterData.Name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  // string MonsterDesc = 3;
  if (this->monsterdesc().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->monsterdesc().data(), static_cast<int>(this->monsterdesc().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Zerium.Data.TESTDATA.MonsterData.MonsterDesc");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->monsterdesc(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Zerium.Data.TESTDATA.MonsterData)
  return target;
}

size_t MonsterData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Zerium.Data.TESTDATA.MonsterData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string Name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string MonsterDesc = 3;
  if (this->monsterdesc().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->monsterdesc());
  }

  // uint32 ID = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MonsterData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Zerium.Data.TESTDATA.MonsterData)
  GOOGLE_DCHECK_NE(&from, this);
  const MonsterData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MonsterData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Zerium.Data.TESTDATA.MonsterData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Zerium.Data.TESTDATA.MonsterData)
    MergeFrom(*source);
  }
}

void MonsterData::MergeFrom(const MonsterData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Zerium.Data.TESTDATA.MonsterData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.monsterdesc().size() > 0) {

    monsterdesc_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.monsterdesc_);
  }
  if (from.id() != 0) {
    set_id(from.id());
  }
}

void MonsterData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Zerium.Data.TESTDATA.MonsterData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MonsterData::CopyFrom(const MonsterData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Zerium.Data.TESTDATA.MonsterData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MonsterData::IsInitialized() const {
  return true;
}

void MonsterData::Swap(MonsterData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MonsterData::InternalSwap(MonsterData* other) {
  using std::swap;
  name_.Swap(&other->name_);
  monsterdesc_.Swap(&other->monsterdesc_);
  swap(id_, other->id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MonsterData::GetMetadata() const {
  protobuf_zerium_2edata_2etestdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_zerium_2edata_2etestdata_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MonsterDataArray::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MonsterDataArray::kItemsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MonsterDataArray::MonsterDataArray()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_zerium_2edata_2etestdata_2eproto::InitDefaultsMonsterDataArray();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:Zerium.Data.TESTDATA.MonsterDataArray)
}
MonsterDataArray::MonsterDataArray(const MonsterDataArray& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      items_(from.items_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Zerium.Data.TESTDATA.MonsterDataArray)
}

void MonsterDataArray::SharedCtor() {
  _cached_size_ = 0;
}

MonsterDataArray::~MonsterDataArray() {
  // @@protoc_insertion_point(destructor:Zerium.Data.TESTDATA.MonsterDataArray)
  SharedDtor();
}

void MonsterDataArray::SharedDtor() {
}

void MonsterDataArray::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MonsterDataArray::descriptor() {
  ::protobuf_zerium_2edata_2etestdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_zerium_2edata_2etestdata_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MonsterDataArray& MonsterDataArray::default_instance() {
  ::protobuf_zerium_2edata_2etestdata_2eproto::InitDefaultsMonsterDataArray();
  return *internal_default_instance();
}

MonsterDataArray* MonsterDataArray::New(::google::protobuf::Arena* arena) const {
  MonsterDataArray* n = new MonsterDataArray;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MonsterDataArray::Clear() {
// @@protoc_insertion_point(message_clear_start:Zerium.Data.TESTDATA.MonsterDataArray)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  items_.Clear();
  _internal_metadata_.Clear();
}

bool MonsterDataArray::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Zerium.Data.TESTDATA.MonsterDataArray)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .Zerium.Data.TESTDATA.MonsterData items = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_items()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Zerium.Data.TESTDATA.MonsterDataArray)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Zerium.Data.TESTDATA.MonsterDataArray)
  return false;
#undef DO_
}

void MonsterDataArray::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Zerium.Data.TESTDATA.MonsterDataArray)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Zerium.Data.TESTDATA.MonsterData items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->items_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->items(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Zerium.Data.TESTDATA.MonsterDataArray)
}

::google::protobuf::uint8* MonsterDataArray::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Zerium.Data.TESTDATA.MonsterDataArray)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Zerium.Data.TESTDATA.MonsterData items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->items_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->items(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Zerium.Data.TESTDATA.MonsterDataArray)
  return target;
}

size_t MonsterDataArray::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Zerium.Data.TESTDATA.MonsterDataArray)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .Zerium.Data.TESTDATA.MonsterData items = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->items_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->items(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MonsterDataArray::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Zerium.Data.TESTDATA.MonsterDataArray)
  GOOGLE_DCHECK_NE(&from, this);
  const MonsterDataArray* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MonsterDataArray>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Zerium.Data.TESTDATA.MonsterDataArray)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Zerium.Data.TESTDATA.MonsterDataArray)
    MergeFrom(*source);
  }
}

void MonsterDataArray::MergeFrom(const MonsterDataArray& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Zerium.Data.TESTDATA.MonsterDataArray)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  items_.MergeFrom(from.items_);
}

void MonsterDataArray::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Zerium.Data.TESTDATA.MonsterDataArray)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MonsterDataArray::CopyFrom(const MonsterDataArray& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Zerium.Data.TESTDATA.MonsterDataArray)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MonsterDataArray::IsInitialized() const {
  return true;
}

void MonsterDataArray::Swap(MonsterDataArray* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MonsterDataArray::InternalSwap(MonsterDataArray* other) {
  using std::swap;
  items_.InternalSwap(&other->items_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MonsterDataArray::GetMetadata() const {
  protobuf_zerium_2edata_2etestdata_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_zerium_2edata_2etestdata_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace TESTDATA
}  // namespace Data
}  // namespace Zerium

// @@protoc_insertion_point(global_scope)
