/////////////////////////////////////////////////////////////
// Generated by the VisualData appbuilder.  DO NOT EDIT!
/////////////////////////////////////////////////////////////

#include "{servicename}_service.h"
#include "{servicename}/{servicename}_system.h"
#include "service_def.h"
#include "protocol.pb.h"
#include "request/{servicename}_request.h"

using namespace {servicename};

//method-begin
gopenngs::erpc::Status {ServiceFullName}Service::xxServiceNamexx(openngs::erpc::ServerContextPtr context, const OpenNGS::{ServiceFullName}::RPC::{requestMsg} *request, OpenNGS::{ServiceFullName}::RPC::{responseMsg} *response)
{
    return ni::app::ProcessCmd<{servicename}::{requestMsg}Process>(this, m_requestSystem, context, request, response);
}
//method-end