/////////////////////////////////////////////////////////////
// Generated by the VisualData modelbuilder.  DO NOT EDIT!
/////////////////////////////////////////////////////////////

#ifndef __{SERVICE_NAME}_SERVICE_H__
#define __{SERVICE_NAME}_SERVICE_H__
#include "singleton.h"
#include "interface/iframe.h"
#include "{servicename}/ni.{servicename}.rpc.erpc.pb.h"
#include "{servicename}/ni.{servicename}.rpc.pb.h"
#include "request/uds_request.h"
#include "common/service_define.h"
#include "service/service_process_system.h"
#include "app/service.h"

namespace {servicename}
{
    class {ServiceFullName}Service : public openngs::app::TERPCService<OpenNGS::{ServiceFullName}::RPC::{ServiceFullName}, OpenNGS::{ServiceFullName}::RPC::{ServiceFullName}RPCClient>,
                       public ni::app::ServiceProcessMngr,
                       public frame::TSingletonWithAutoCreate<{ServiceFullName}Service>
    {
    public:
        {ServiceFullName}Service() { m_strServiceName = {SERVICE_NAME}_SERVICE_NAME; }
        virtual ~{ServiceFullName}Service() = default;

        virtual void Init(){};

    private:
		//method-begin
		virtual openngs::erpc::Status xxServiceNamexx(openngs::erpc::ServerContextPtr context, const OpenNGS::{ServiceFullName}::RPC::{requestMsg} *request, OpenNGS::{ServiceFullName}::RPC::{responseMsg} *response);
		//method-end
        
    };

} // namespace {servicename}

#endif /* !__{SERVICE_NAME}_SERVICE_H__ */