// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: OpenNGS.Suit.Data.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable 0612, 0618, 1591, 3021
namespace OpenNGS.Suit.Data
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SuitData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public SuitData()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint ID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::OpenNGS.Suit.Common.EQUIP_SUIP_TYPE SuitType { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsPacked = true)]
        public uint[] ConsistEquipID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SuitDataArray : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public SuitDataArray()
        {
            items = new global::System.Collections.Generic.List<SuitData>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<SuitData> items { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SuitBuff : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public SuitBuff()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint ID { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public float BuffData { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SuitBuffArray : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public SuitBuffArray()
        {
            items = new global::System.Collections.Generic.List<SuitBuff>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<SuitBuff> items { get; private set; }

    }

}

#pragma warning restore 0612, 0618, 1591, 3021
#endregion
