// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: chat_service.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable 0612, 0618, 1591, 3021
namespace Rpc.Game
{

    [global::ProtoBuf.ProtoContract()]
    public partial class GetChatReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public GetChatReq()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::OpenNGSCommon.ChannelInfo channel { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint seq { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetChatRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public GetChatRsp()
        {
            infos = new global::System.Collections.Generic.List<global::OpenNGSCommon.ChatInfo>();
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<global::OpenNGSCommon.ChatInfo> infos { get; private set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SendChatReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public SendChatReq()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public global::OpenNGSCommon.ChatInfo chat { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SendChatRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        {
            return global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        }
        public SendChatRsp()
        {
            OnConstructor();
        }

        partial void OnConstructor();

        [global::ProtoBuf.ProtoMember(1)]
        public uint result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::OpenNGSCommon.ChatInfo chat { get; set; }

    }

    [OpenNGS.IRPC.Configuration.Service(@"Rpc.Game.ChatService")]
    public partial interface IChatService
    {
        global::System.Threading.Tasks.Task<Rpc.Game.GetChatRsp> GetChat(Rpc.Game.GetChatReq value, OpenNGS.IRPC.ClientContext context = default(OpenNGS.IRPC.ClientContext));
        global::System.Threading.Tasks.Task<Rpc.Game.SendChatRsp> SendChat(Rpc.Game.SendChatReq value, OpenNGS.IRPC.ClientContext context = default(OpenNGS.IRPC.ClientContext));
    }

}

#pragma warning restore 0612, 0618, 1591, 3021
#endregion
